### ISSUE TITLE
Can't get ink sacs

### ISSUE THREAD

**Issue by aRvi0nE** [Darkosto/SevTech-Ages#1002]
Greetings, im having an issue with crafting a fluid bladder, i had been through this part already on friend's server that was on version 3.0.1, but now im playing on a single player on version 3.0.3 and i can't get an ink sac, in version 3.0.1 you could grind a black lotus to make a black powder and then turn it into an ink sac, but as of version 3.0.3 that recipe has been removed and squid just don't spawn on my world.
Im also using optifine if thats relevant information.

Thanks in advance.

**Comment by artdude543** [comment]
You're going to have to explore your world more to find the spawning locations for Squid. On all my test worlds they spawn quite often. You may need to travel in an Ocean tho. But that's the only method of getting Ink Sacks as current.

**Comment by aRvi0nE** [comment]
i was in a ocean, and they didnt spawn

**Comment by artdude543** [comment]
I tested this in an ocean and there were dozens of them. This was tested in default world gen and realistic.

**Comment by aRvi0nE** [comment]
now im back on my friend's server now in version 3.0.3 and i found squid in a small river near a black forest, but my friend now is also looking for squid and can't find it anywhere

**Comment by aRvi0nE** [comment]
it's been like an hour and he hasn't found any

**Comment by aRvi0nE** [comment]
we tried switching difficulties still no luck

**Comment by aRvi0nE** [comment]
why did you close the issue this is clearly not resolved

**Comment by Darkosto** [comment]
I'm going to just stop this issue right here.

Minecraft RNG is not a pack issue, it's an issue with your luck. Squid spawn just fine. Like anything you're looking for it will not always spawn when you want it to. Sorry, that's how it works.

The recipe you're referring to to create ink sacs was an exploit and that bug was fixed. 

Closing and locking this issue. Please report actual bugs and not you're lack of luck finding ink sacs.

Thank you.
