### ISSUE TITLE
Aqueduct and flowing rivers dont work together

### ISSUE THREAD

**Issue by Skullywag** [Darkosto/SevTech-Ages#1114]
Had a look about for others reporting anything in this area, bar some weird behaviours with the aqueducts no one else has reported this and im not sure if im doing anything wrong but a couple of us have tried this and cannot get it to work.

Basically putting an aqueduct under a flowing river (theyre infinite water right?) doesnt fill the aqueduct. Ive put a water source block from creative over it and it fills fine, are flowing river blocks supposed to act as infinite water sources?

If they arent Im not sure I see the point of the aqueducts. Any steer here?

**Comment by cheesealmighty** [comment]
I was disappointed to see that I couldn't use the mountain spring to bring water to my settlement with aqueducts as well.

It's because aqueducts need vanilla full blocks of water, while Streams mod has its own nondecaying stream water. That's why it doesn't work. I couldn't see an option in Better with addons config to make aqueducts with streams of water.

**Comment by artdude543** [comment]
This was fixed and confirmed that it's working as intended in 3.0.4
