### ISSUE TITLE
Gold/Rockcrystalore not spawning

### ISSUE THREAD

**Issue by Lyriox** [Darkosto/SevTech-Ages#1143]
I've traveld about 5k BLocks in every direction and i did found 2 gold ore samples at the top but there was no ore under it same and the rockcrystal only at the top around 8 sample pieces

-> lack of progression

**Comment by Ambaire** [comment]
There should have been gold down there. Did you go to the top of the y range where it spawns, dig a cross hatch on the chunk and a 1x2 around the edge and check every block with the tier2 dowsing rod?

As for rock crystal, I heard that the dowsing rod doesn't detect it. It spawns from y3-11, so you'll need to dig a classical search pattern per vanilla minecraft.

**Comment by justinrusso** [comment]
did you dig directly down expecting an ore to be there? or did you look around the ENTIRE chunk that the sample is in?

**Comment by Dystilled** [comment]
Would think this is to do with the ore generation issues that Dark is currently looking in to. 

I can also confirm the Samples on top but no ore below issue with gold. 

Found a vein, dug down to just above where gold spawns and dug out the entire chunk, dowsing rod did not detect anything anywhere below. Went down another 10 blocks, Dowsed, nothing, Rinse and repeat. Empty chunk, nothing on the borders either.

**Comment by xanderhunter** [comment]
I have also now just strip mined a chunk from y=32 to bedrock to try and find the ore but couldnt find it

**Comment by daddy77gaming** [comment]
If the sample is there, the ore is as well..
be sure you are updated to 3.0.3, gold gets douced, rock crystal does not..

![2018-03-31_11 35 52](https://user-images.githubusercontent.com/31905330/38162652-542134ca-34e5-11e8-900d-50fdaa03d9fc.png)

![2018-03-31_11 58 19](https://user-images.githubusercontent.com/31905330/38162637-2897dbc4-34e5-11e8-9d19-ecee87cd590e.png)

![2018-03-31_11 59 06](https://user-images.githubusercontent.com/31905330/38162643-34d58800-34e5-11e8-93ae-f0d891ce7f2e.png)

**Comment by Ultimaheart4** [comment]
so i found rock crystal and gold. actually if found 8 gold veins, 3 lapis veins and 3 rock crystal veins. my issue comes from having no iron veins. no iron can be found on the surface anywhere. ive been searching for hrs. 100s of blocks away from my base and everything. 
![image](https://user-images.githubusercontent.com/29152256/38165009-3980bc62-34db-11e8-86a8-68ad67c93f7b.png) this is a screen shot of my map. all of the red marks are ore deposits ive confirmed. ive also found a lot of copper, tin, and coal. wondering if its because this world is from before 3.0.3? or if there is another issue? i was also able to detect bauxite with the dowsing rod for age 2? but havnt been able to see said ore. only a lot of salt.

**Comment by xanderhunter** [comment]
![2018-04-03_02 36 59](https://user-images.githubusercontent.com/11369206/38235815-073f28b0-36e8-11e8-81fd-169e7d20b4fa.png)
This is a photo of a completely cleared chunk that had a sample init from 30 to 8, there was no gold ore.

**Comment by artdude543** [comment]
We made a tonne of changes in 3.0.6 to Ore generation but it will only take effect in new chunks. If you still have the issue in **new** chunks in 3.0.6 please make a new issue.
