### ISSUE TITLE
Rice Bread ignores fullness

### ISSUE THREAD

**Issue by MechaDom** [Darkosto/SevTech-Ages#1167]
* Modpack Version: 3.0.3
* Java Version:  1.8.0.151 64bit
* Launcher Used: Twitch App: Native Launcher
* Resourcepack Enabled?: Yes.  Soartex Fanver
* Optifine Installed?: No

Rice Bread ignores fullness allowing you to eat to full saturation even when "Full" and beyond.
Same issue with Cooked Bear Meat, Horse Meat, and Wolf Meat from Primal Core.
Have not tested all the food but so far other meats and foods work normally.

**Comment by Ambaire** [comment]
I like that this is a thing. Makes it much easier to do blood magic or heal up while in combat since you don't have to wait for it to deplete saturation to 1/2 shank gone so you can eat again. If it would promptly deplete that half shank immediately after depleting saturation, that would be a lot nicer.

**Comment by Targren** [comment]
#1139

**Comment by MechaDom** [comment]
Thank you Targen.  My search didn't find that one

**Comment by Darkosto** [comment]
Closing this because I'm not worried about it. Thanks for the report.
