### ISSUE TITLE
Twilight Forest- Did not get death compass

### ISSUE THREAD

**Issue by Dystilled** [Darkosto/SevTech-Ages#1175]
## Issue / Bug
Died to TNT in the secret room of Labrynth (due to pressure plate flying across the room and landing on another plate. 

## Current Behavior
Respawned without a death compass, instead had my Steeleaf Pick in 1st slot. 

## Possible Solution
I believe I was carrying a charm of life (maybe the issue?)

## Steps to Reproduce (for bugs)
Blown up by tnt in secret room while holding a steeleaf pick?

## Context
No death compass to find grave. 

## Your Environment

* Modpack Version: 0.3
* Java Version: 8.2
* Launcher Used: Twitch
* Resourcepack Enabled?: Soartex Fanver
* Optifine Installed?: Yes

**Comment by Darkosto** [comment]
Will investigate with @vadis365

**Comment by MongoTheElder** [comment]
Can confirm the same issue with the charm of keeping

**Comment by vadis365** [comment]
Not sure much can be done about this, I use the drops event and they cancel it - it's probably a priority issue. It is their charm of keeping - seen it a few times on streams now.

**Comment by Ebullio** [comment]
well in my case the charm of keeping stopped my grave from spawning aswell, rip 64 ingots and steelleaf

**Comment by vadis365** [comment]
Added a bit of code so the player will drop the compass on re-spawn if their inventory is full - nothing else I can do about this if it doesn't solve the 'no compass issue' - It may be at TF's end to fix or for Darkosto to remove the charm of keeping from the pack if it causes a fundamental issue like this.

**Comment by vadis365** [comment]
looks like we have it fixed in dev now.

**Comment by justinrusso** [comment]
@vadis365 what fixed this so we can add it to the changelog?

**Comment by Frunblumglin** [comment]
@vadis365 
i was playing in the new version of the pack... 3.0.6 and just accidentally killed myself using a dagger of sacrifice with a charm of life 1 in my inventory... i spawned back in, the death waypoint spawned, but i had no grave... and the death compass that spawned pointed to my 2nd latest death in the hunting dimension... i just lost many tinker tools that i spent hours upgrading and making to my liking... and pretty much everything else useful i had in the pack while in my own base. Needless to say i'm probably quitting the pack here since all my hard work just got voided and i'm too lazy to make backups... but wanted to let you guys know that this charm of life bug is still a thing.

**Comment by justinrusso** [comment]
Or you can make backups instead... or also use `/tmg_restore` and see if its there.
