### ISSUE TITLE
All advancements disabled/reverted after loading save file

### ISSUE THREAD

**Issue by shoulderdeep** [Darkosto/SevTech-Ages#1186]
I got halfwayish through Age 1 and was just farming shoggoth skins at one of their lairs when food arrived IRL. I built a 3x3x3 around me, saved and exited to eat. After I loaded my save file, I was at my base with an inventory I seemed to have had yesterday (about 8ish hours of gameplay ago). Everything in my base was fine, I had my bronze ingots still and what not, but it all was registered as "unidentified items" and my NEI only had 3 pages total unlocked. My advancement screen still showed everything i've accomplished but I could not use anything past age 0. Remaking any of the age 0 advancements would not re-trigger the advancement either. 

This is single player, no lan or server. I have backed up my save and uninstalled/reinstalled the modpack. 
![2018-03-31_15 08 37](https://user-images.githubusercontent.com/37962508/38166683-f60b399c-34f5-11e8-8baf-2745aa3e8a6c.png)
![2018-03-31_15 08 54](https://user-images.githubusercontent.com/37962508/38166684-f6180dd4-34f5-11e8-8cf4-803e68945b8c.png)
![2018-03-31_15 08 59](https://user-images.githubusercontent.com/37962508/38166685-f623b74c-34f5-11e8-841b-9a055f79690a.png)
![2018-03-31_15 09 11](https://user-images.githubusercontent.com/37962508/38166686-f62e94b4-34f5-11e8-8d07-286f60a01477.png)

Modpack Version: 3.0.3
Java Version: 8.0.1610.12
Launcher Used:twitch
Resourcepack Enabled?: no idea, i use default
Optifine Installed?: no

**Comment by justinrusso** [comment]
Have you tried updating to 3.0.4?

**Comment by shoulderdeep** [comment]
Yea, once 3.0.4 dropped I updated it but nothing has changed

**Comment by shoulderdeep** [comment]
So I had made a new world and progressed to around the same point, got through to the beyond world and made blood magic so it was a few advancements further. I saved and exited the game to go do family easter stuff, come back and load the game to find my new world is also messed up in the same way. everything I had on me reverted to some other past point of the save while my world stayed current. This time I am still able to see age 1 items but I theorize its because this past inventory save was already in age 1, since it had copper in it. 

If you need more info let me know what and where to get it from as i dont know much about files and stuff.

**Comment by Jandakast** [comment]
This sounds like Minecraft is unable to update/save the level.dat file in your save. This sometimes happens when you are low on disk space, or if you have an antivirus application that creates a file lock when using Active Protection scans for recently updated files. Inventory, Game Stage Progression, and location are all stored in the level.dat file. Where as the Advancements shown in the GUI are stored in the saves\wordname\advancements folder. 

If you can, try excluding your SevTechAges\saves folder and files from active scans in your Antivirus program. Also adjust your power settings so that your hard drive is set to never turn off. 

I am closing this issue as I do not believe this is not an issue with the pack itself. 

![image](https://user-images.githubusercontent.com/19498789/38395281-31201bf2-3900-11e8-981b-c3fd1f389715.png)
