### ISSUE TITLE
Possible Modpack Optimizations Avaliable?

### ISSUE THREAD

**Issue by jhagrid77** [Darkosto/SevTech-Ages#1194]
## Issue / Bug
The issue that I'm having is the fact that this pack seems so amazing but is very resource intensive. 

## Current Behavior
Currently the pack does not want to launch to the main menu. In fact, it doens't even finish loading up. I even updated the performance enhancing mods and looked through their settings to improve some that I already knew of, but obviously there are a lot.

## Possible Solution
Change settings? Remove buggy mods?

## Context
Now I know that the more mods that you add and such, the more resources that are required. However, I see that this pack requires between 6GB and 8GB of RAM which, to me, seems like quite a lot. I currently only have 4 on my computer and upgrading isn't too easy. But back to the problem. I was wondering if there is any optimizations that could be made, either in the pack itself or per client that could make this pack run in 3GB or so of RAM?

## Your Environment
* Modpack Version: 3.0.4
* Java Version: The latest 8 version.
* Launcher Used: Curse
* Resourcepack Enabled?: No.
* Optifine Installed?: Yes.

**Comment by Targren** [comment]
I had good luck with disabling most of the aesthetic mods locally. MultiMC can disable them right in the launcher, don't know about other launchers, but you can manually change the file name in the "mods" folder to add ".disabled" to turn it off for your client (may or may not work on servers)

* Smooth Font (This is a big one)
* Mo'Bends (The creepy spiders are cool, but otherwise, not worth the resources IMO)
* FancyBlockParticles
* BetterFoliage (Really, there's nothing about this one I liked. Can also be disabled in-game by pressing F8 and twiddling its options apparently)

Be warned: It's still a pretty hefty modpack without them, though.

**Comment by justinrusso** [comment]
We are working on reducing any issues we find, but we cannot and will not be able to make this work for everyone. This is going to be resource intensive. The best you can do is things @Targren recommended, as well as trying to reduce setting with the help of optifine, for example.
