### ISSUE TITLE
[3.0.4] [Recipe] BWM Sawdust does not create paper

### ISSUE THREAD

**Issue by Targren** [Darkosto/SevTech-Ages#1205]
## Issue / Bug

JEI shows a recipe for 3 mekanism:sawdust to create paper. Using Better With Mods sawdust doesn't work. 

## Current Behavior

Tested and confirmed that mekanism:sawdust recipe works in Age 2. 

## Possible Solution

oreDict sawdust?

Since Age 2 still has 3 sugarcane recipe, I assume this is an oversight rather than a balancing issue since it's trivial to get all the paper you'll ever need with that one. 

## Your Environment
* Modpack Version: 3.0.4

**Comment by Darkosto** [comment]
I just spent a few minutes looking into this and I'm confused because the recipes are specifically set to ONLY use BWM saw dust.

"Since Age 2 still has 3 sugarcane recipe" <-- This does exist in this pack: 

![image](https://user-images.githubusercontent.com/10309699/38177839-b3af56ac-35d4-11e8-9437-30ae97bfd9c9.png)

I'm fairly certain the bug is on your end due to a bad install. I recommend reinstalling the pack to the latest version 3.0.4 and trying again.

I am going to ask @justinrusso to take a look at the Mekanism Precision Saw to output BWM sawdust and completely remove Mekanism Sawdust from being needed/used.

**Comment by Targren** [comment]
Weird. Okay, I'll try it again when I get home . I think you may be right, though. I've started being able to craft planks in 2x2 from logs again, too

**Comment by justinrusso** [comment]
Sounds to me like your scripts are erroring. I'd strongly suggest re-installing. If this does not fix it, please provide your crafttweaker.log file via pastebin or gist.github.com

**Comment by Targren** [comment]
There *was* an error in my scripts that was letting the reeds-to-paper recipe work (I'd disabled the death compass mod). That's fixed now that I reenabled it, but the BWM sawdust recipe still isn't working.

[Here's the crafttweaker.log](https://gist.github.com/Targren/a30b77d91fe48447b44a5bfbedfe71c5). I  couldn't find any errors in it now, but maybe you'll see something.

**Comment by Targren** [comment]
Derp. Nevermind. Fixing the scripts removed the sawdust recipe, too. Darn it.
