### ISSUE TITLE
Improved Backpack overrides/deletes Inventory

### ISSUE THREAD

**Issue by bearY0** [Darkosto/SevTech-Ages#1266]
I just had a very weird and annoying bug where my Inventory was replaced with my Improved Backpack's Inventory effectively deleting my Inventory.

![2018-04-01_23 03 24](https://user-images.githubusercontent.com/13459228/38177474-985152a6-3602-11e8-8290-edfecaff893c.png)

As you can see my Armor was also replaced with stuff I had in my Improved Backpack (was a Tier 2 Backpack, if it helps). It also replaced my hotbar, but the first 2 Items (Sword and Pickaxe) were first replaced but then reappeared, dont know how to describe it. The last 2 slots were the Backpack which was itself replaced with the angry pebbles and my atlas which is gone now. Unfortunately I don't know how to reproduce it. I was just running through the Betweenlands when it suddenly happened. Still wanted to share it because it really sucks, maybe you can look into it.

* Modpack Version: 3.0.4
* Java Version: 1.8.0_25
* Launcher Used: Twitch
* Resourcepack Enabled?: No
* Optifine Installed?: Yes - OptiFine_1.12.2_HD_U_D1

**Comment by artdude543** [comment]
Hello!

This appears to be an older issue on an old version of the modpack. This issue may have been fixed in later versions of the modpack, so we recommend that you update! If however, you are still having the same issue.

Please re-file an issue following the template and provide as much detail as you can. 

Thanks in advance and thank you for playing SevTech Ages!
