### ISSUE TITLE
Add a bit more text to a few advancements

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#1277]
Betweenlands Tool Adv. 

Oil Processing adv.

**Comment by Dystilled** [comment]
Can I suggest adding text to the Coal Engine advancement (St2) regarding the Carminite reactor? 

Found myself completely lost as to how to get the Carminite Reactor for advancement even after clearing most of the Twilight forest because the 2 ur-ghast towers I had been in had not spawned a Carminite Reactor. 

Looking at the discussion in Discord it seems many others hit the same wall.

**Comment by Darkosto** [comment]
Should be all good. Will keep an eye on new ones that need more clarification.
