### ISSUE TITLE
Geolosys ores not spawning in betweenlands (Samples still do)

### ISSUE THREAD

**Issue by IronEE** [Darkosto/SevTech-Ages#1286]
Last night whilst playing I came across a gold sample in the betweenlands, and dug down to the level the gold advancement described and mined, and mined, and I found no ore, so I decided to install World Stripper and checked in a three chunk radius and found no geolosys ore, only bewtweenlands ores. Then I traveled in one direction to generate new chunks until I found a rock crystal sample. I stripped in a three chunk radius, and there was no ore underneath either.

* Modpack Version: 3.0.4
* Java Version: Java 8 161
* Launcher Used: Twitch
* Resourcepack Enabled?: no
* Optifine Installed?: no

**Comment by IronEE** [comment]
Also, I haven't been able to test other ores because I am only in stage 2

**Comment by traumafox** [comment]
Experiencing the same issue, however gold does appear to be spawning in the Beneath dimension, albeit without surface samples. Unsure if this is intended.

**Comment by Hebbu** [comment]
Gold does spawn in the overworld

**Comment by TitanGuard** [comment]
I have found Gold, Rock Crystal, and Lapis samples in the BetweenLands and dug down to the stated levels they spawn at, circling the chunk all the way down, and tested for ores with the prospect tough dowsing tool and found zero of any ore of each type even after digging it out to see if the tool was just not working correctly, but with no luck, its just not spawning. this is SevTech Ages version 3.0.4 i was playing on

**Comment by sesgoe** [comment]
I have found Golg, Rock Crystal, and Lapis samples in the Betweenlands too, and cleared the chunks in creative mode just to confirm no ore was present.

Based on poking around in the config files, inside of geolosys.cfg, it seems this bit:

"user entries" {
        S:"Blocks mineral deposits can replace" <
            minecraft:stone:0
            minecraft:stone:1
            minecraft:stone:2
            minecraft:stone:3
            minecraft:dirt:0
            rustic:slate:0
            chisel:marble2:7
            chisel:limestone2:7
            chisel:basalt2:7
            primal:schist_blue_stone:0
            primal:ferro_stone:0
            primal:mud_wet:0
            primal:terraclay_block:0
            primal:sarsen_stone:0
         >

Is to blame because based on a cursory reading of how it works, it uses that config to determine what block types to "override" with ore, and no betweenlands blocks are "allowed" to be overwritten, so it spawns the samples but the betweenlands stone types never get overwritten.

Could be completely wrong, but wanted to help point in a direction if it helped out.

**Comment by justinrusso** [comment]
This should be fixed in 3.0.6

https://minecraft.curseforge.com/projects/sevtech-ages/files/2549553
