### ISSUE TITLE
Betweenland issues

### ISSUE THREAD

**Issue by Turmfalke2** [Darkosto/SevTech-Ages#1291]
## Issue / Bug
The "The Betweenlands" advancement incorrectly states that the tools bought from my dimension into the Betweenlands will not effective. In fact they are far superior! A weedwood pickaxe has a mining speed of 2, a durability of 80 and suffers from the weedlands decay mechanic. Compared to that a simple bone pickaxe from tinkers has mining speed 5, 290 durability.  
From what I can tell without bring a hatches from the overworld I wouldn't even be able to acquire the wood for the betweenlands pickaxe.
Maybe the betweenalnds endgame tools will be better, but as it stands the tooltip is highly misleading/incorrect.  
Also it seems like my normal food carrots/baked potatoes is also fine to consume in the Betweenlands.

In addition to that, maybe the advancement for creating the portal should mention that the portal is quite huge? I could see quite a few people expecting a normal nether portal sized portal and due that destroying their base. Luckily in my case it was just the cow stable.

## Your Environment
* Modpack Version: 3.0.4
* Java Version: 1.8
* Launcher Used: MMC
* Resourcepack Enabled?: Yes, thank you mojang.
* Optifine Installed?: No

**Comment by Turmfalke2** [comment]
Also it would be nice if we could sleep in the dimension. As it stands it is already really dark during the day and when the sun sets in the overworld is pretty much pick black in the Betweenlands. This severely limits the area the player can explore in the dimension.

**Comment by Turmfalke2** [comment]
OK this is pretty much unplayable without going into creative. 
I died in the Betweenlands because something killed me magic. I expected I would respawn in the overworld similiar to how you do when you die in nether/end, instead I respawned ~30 blocks below the water surface in a swarm of angry fishes that instantly murdered me again.

How is this supposed to work?!

**Comment by borg286** [comment]
It seems that the creators of the Between Lands mod know about your spawn point being somewhere random in the Between lands. Their guide to survival make a point that getting a bed is of utmost importance: http://the-betweenlands.wikia.com/wiki/Basic_Guide_to_Survival
I feel it is overly harsh, but that seems to be the name of the game for this world.

**Comment by GoryMoon** [comment]
When using non BL tools in the dimension they are slowed down and weapons do less damage whilst in the dimension.
The food rotting have been disabled for this pack so that's why they aren't rotting.

The not respawning near the portal when dying has been fixed in a newer version of BL and will probably be in the next pack version.

**Comment by tritechnik** [comment]
To add to the above comments, so is the official stance that a single death renders your world unplayable without editing the save file? Seems like a gamebreaking bug. I died to a crab army/leech as I was instructed to bring nothing valuable. So I went to check out the area, and bam dead. Now I have no idea where my portals are and just respawn in the middle of no where.

**Comment by GoryMoon** [comment]
No, the issue of not respawning near the portal have been posted before and fixed. #1146

**Comment by justinrusso** [comment]
Updated to https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2548656

Will be in 3.0.5

**Comment by Darkosto** [comment]
Okay, I just need to comment on this one quickly because there is just so much misinformation in this OP. I hate to prolong an issue but this needs to be said.

1. Please do not just stick multiple issues into an issue on this tracker. 1 issue for 1 bug/problem. Do not just load in as many as you can think of.

2. "The "The Betweenlands" advancement incorrectly states that the tools bought from my dimension into the Betweenlands will not effective. In fact they are far superior!" 

Sorry, but how? Because you checked out stats on the tooltips? Did you notice that non-betweenlands tools are SEVERELY slowed down and weapons attack for negligible amounts? 

3. Foods do not rot. This has been done to allow the player to maintain their nutrition levels without losing values while learning the betweenlands and its food.

4. The portal creation wand literally tells you if it does not have enough space:

![image](https://user-images.githubusercontent.com/10309699/38429752-54739e5c-398d-11e8-8d59-0ed8468b05ca.png)

It won't destroy anything in your base because it will fail on portal creation. There's no need to tell players this because the wand gives you the information. If you are unfamiliar with how something works then do not place it near something you care about. I think that goes without saying. 

5. The only issue in this thread that is going to be considered for a change is being able to set your spawn point to stop death loops. 

Again, stop just adding on issues to a post about 1 bug. It unorganized and guarantees the issue will not be properly fixed since it adds way too much information to what should be 1 issue.

**Comment by Turmfalke2** [comment]
> Sorry, but how? Because you checked out stats on the tooltips? Did you notice that non-betweenlands tools are SEVERELY slowed down and weapons attack for negligible amounts? 

No, I measured the time to dig a tunnel/chop down a tree. My Tinkers bone pickaxe is far superior.  Also for weapons: The mobs in this pack have a health bar above them, you can clearly tell how much damage they do.

> The portal creation wand literally tells you if it does not have enough space: 

Well it didn't for me, it clipped throw a wall of my cow stable and killed several animals.

**Comment by Turmfalke2** [comment]
I am not sure what to do if you just insist on not trusting me.

Here we have 24 blocks of betweenstone in the betweendlands.
![2018-04-07_11 22 36](https://user-images.githubusercontent.com/5174562/38453458-6c4c8efc-3a56-11e8-9ce1-1d228d58ebdd.png)

With a weedwood pickaxe it took me 36 seconds to mine them, with a tinker's construct bone pickaxe (bone head,bone binding, wood tool rod) it took me 18 seconds to mine them.  

Now please explain me again how my non-betweenlands tool is SEVERELY slowed down.
