### ISSUE TITLE
Lag spikes in 3.0.4 update

### ISSUE THREAD

**Issue by captianfrost** [Darkosto/SevTech-Ages#1338]
So I don't know if someone can help me but whenever I try to run the modpack on my PC it starts having lag spikes. I tried all the lag inducing factors I could think of like clouds and render distance. I can run a lot of other mods like sky factory and hexxit. I got the mod off the twitch launcher. I'm playing with the latest version of java and I'm on modpack version 3.0.4. I can still run the mod but the tiny lag spikes that I'm experiencing are very annoying. I looked through the other posts I didn't see my problem so if I missed a post if you could link it that would be helpful cause I just searched "lag" and it didn't come up.
Thanks!

**Comment by Dystilled** [comment]
Are you running twitch/youtube/some other video service? I've noticed eventually these things cause my MC to lag spike pretty hard in this pack.

**Comment by LemADEC** [comment]
press F3 and check your memory consumption

**Comment by artdude543** [comment]
This is something which is really out of our control. As it's a "user" error rather than the modpack. What I could suggest is allocating more memory to the game if you had not already. This modpack is not like other packs and is made to Sev's spec in terms of being a hungry pack to be able to run.

Check that your Java is the latest 8 version, graphics drivers are up to date you're using the [Java args](https://pastebin.com/nV8aHRLE) are recommended. You could try disabling SmoothFont and/or install Optifine (But I don't recommend personally) Other apps running in the background will affect your CPU time that the game wants to use. But other than that we can't really help from the pack side of things. It's not a pack designed to run on "lower" end machines.

The last thing would be to lower the settings in the game but you may have tried this already. I hope this helps somewhat and you manage to get it more playable for yourself.
