### ISSUE TITLE
Astral Sorcery is completely broken on world made in ver 3.0.1

### ISSUE THREAD

**Issue by Mack1410** [Darkosto/SevTech-Ages#1354]
## Issue / Bug
* Astral Sorcery tome does not have exploration category, which was available before version update
* Luminous Crafting Table does not recognise any recipes, and will not craft under any condition

## Steps to Reproduce (for bugs)
* Couldn't reproduce it,works on a freshly made world

## Context
Completely locked out of progression since I cannot read the book or complete main quest since the Luminous Crafting Table does not work, seems like Astral Sorcery does not detect progress

## Your Environment
* World created in 3.0.1,updated to 3.0.4
* Modpack Version:3.0.4
* Java Version:1.8.0_161
* Launcher Used:Twitch launcher
* Resourcepack Enabled?:Soartex Fanver Modded
* Optifine Installed?:yes

**Comment by extrenix** [comment]
If I may add, I was able to craft the luminous table the other day but it cannot be move. Using a pickaxe on the table totally destroy it

**Comment by Mack1410** [comment]
Could've just made another thread, but it is probably not bugged. Stone pickaxes cannot pick up this table. You need a higher level tool

**Comment by Jandakast** [comment]
This should be able to be fixed by running the command "/as research @p BASIC_CRAFT" You will need cheats enabled or be an OP on the server. You can replace @p with the user name if you are on a server and this needs to be ran for others. This command only unlocks the Exploration category. 

If you unlocked multiple categories prior to the update you will likely need to redo some of the Astral Sorcery specific progression but this command should allow you to continue without creating a new world.

**Comment by Mack1410** [comment]
The command did it, thank you. I wish I knew what caused one specific world to not progress the mod to help fix this problem, but I have yet to find any way to recreate the bug since it works on any new world. Should I keep this thread open as it might still happen to someone?

**Comment by daddy77gaming** [comment]
If I may add, AS has a pretty common bug where starlight stops working.. usually fixed by a restart of the pack ( not a reload)

**Comment by Jandakast** [comment]
Your Astral Sorcery player data was probably corrupted somehow. This has happened to me in the past in other packs. I am closing this issue as it appears to be resolved.
