### ISSUE TITLE
Recipe conflict Flint Pickaxe and Flint Work Blade

### ISSUE THREAD

**Issue by RTHauke** [Darkosto/SevTech-Ages#136]
Issue:  The Flint Work Blade has 2 recipes.  One with a piece of flint and a second that is the same as the flint Pickaxe.

Pack version: Alpha 5
Logs: No
Crash: N/A
Launcher:  MMC-Linux

**Comment by Darkosto** [comment]
Interesting. I think something went wrong in your version. This is not the case in my dev version since both recipes are removed and replaced with custom recipes that are very different. 

![image](https://user-images.githubusercontent.com/10309699/31577021-04026ff2-b0d5-11e7-9500-2c0a5d5322bf.png)

![image](https://user-images.githubusercontent.com/10309699/31577028-1de65b86-b0d5-11e7-9007-925e8d74b75d.png)

I'll keep an eye on it, if during the update this still happens let me know.

**Comment by RTHauke** [comment]
Ok, I'll try a fresh install and see if I see it again.  There were other recipe issues that popped up related to other flint tools, so may be something happened to the script on my side.  Thanks!

**Comment by RTHauke** [comment]
I was able to recreate this on a fresh install of Alpha5. (Now that was an MMC import of the Twitch export, so may be that's the issue.)  Anyway, it does not appear to be an issue in the MMC export of Alpha6 I just downloaded so I'm closing the issue.
