### ISSUE TITLE
Server lag - seems to be related to abyssal mobs?

### ISSUE THREAD

**Issue by Sabster** [Darkosto/SevTech-Ages#1373]
I did search the GitHub, and the only other comment about lag was closed (but I couldn't figure out why it was closed...)

This has happened multiple times - 3.0.4 - the only fix is to exit the game client, and go back in.  I'm 90% sure it has something to do with abyssal mobs as they are always present when the lag hits (the lizard demon things that make slime trails (I see names with lesser ...  just starting out, so can't get too close.)

There's no crash reports - I couldn't use pastebin for log (too big), so attaching here (sorry, couldn't figure out where else to put it...)
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1873630/latest.log)

What happens is the game is running fine, and then I near an abyssal lair (dark tunnel, lots of the demon things in it) and instantly get lag - everything  becomes very sluggish and as I said above, only fix is to exit the game client and log back in.  The server itself doesn't seem to be affected...

When I exit the area with the demon lair thing - the lag continues (even when the chunk has been unloaded...)

**Comment by Sabster** [comment]
Btw - no other mods installed only that a fresh copy of SevTech Ages...

**Comment by mcdodge34** [comment]
Just commenting since I see this kind of issue in every single modpack that try to use other mods that have mobs in them, like Mo'Creatures, Abyssal mobs and many more, if it add any mobs, you can be 100% sure you'll have problems eventually since they always end up causing lag and fps problems to a point I simply give up if the modpack requires in quests that some materials be gathered or farmed from theses mobs, or I end up removing the mod to solve the issue pure and simple. And I've tried a fair share amount of modpacks, its really annoying since I really want to enjoy theses mobs and fight them, but if my fps and tps go below 10 while they are at 20 tps and between 60 and 120fps in all parts of the world without the mobs, I say there's something wrong and its common to all mods that add mobs to the game, what is beyond my understanding there, Any clue would be welcome.

**Comment by artdude543** [comment]
We made some changes and tweaks along with mods for 3.0.7 so this could be helped a bit. But these issues are always going to be a thing. Even with massively performant mods. It's just one of the many flaws of MC itself.
