### ISSUE TITLE
Crash When Drinking Wine

### ISSUE THREAD

**Issue by Zarathaen** [Darkosto/SevTech-Ages#1408]
Modpack Version: 3.0.4
Java Version: 1.8.0_161-b12
Launcher Used: Twitch
Server/LAN/Single Player: Singleplayer (The world is also used for MP with hamachi, but was not at the time)
Resourcepack Enabled?: No
Optifine Installed?: Yes

I'm playing the latest version of the pack in a world with my girlfriend. Today I was on, in age 2, working on our house. I didn't have it open for multiplayer, and it was just me online. I brewed some wildberry wine from Rustic and bottled it. When I drank it, the game immediately crashed. The only thing I found odd was that I made two different batches, of different qualities, but when I bottled them, they allowed stacking. Rustic has a function where wine has a "quality" when brewed, and you get different effects depending on how high or low the quality is. I have no clue why this caused a crash, but here's the crash report, I hope it makes more sense to you guys than it does to me.

https://pastebin.com/xufLc2hH

Thanks in advance, I'm loving the pack otherwise.

**Comment by Zarathaen** [comment]
I was able to make more wine of the same type. I didn't realize, but earlier, only the first batch of wine I made displayed the "quality". The second batch's quality wasn't listed, and when I bottled both and combined them, the quality disappeared from the first bottle. So from what I can tell, something glitched and caused them to not have a quality. Since quality affects the effects the wine gives to the player, I imagine it tried to figure out what to do, didn't know what effects to grant, and crashed. In the two batches I recently made, the quality didn't vanish. When I drank one, it applied the correct effects and didn't crash. It appears the bug has to do with the quality vanishing and/or not being applied when the wine is created.

**Comment by xXNiugaXx** [comment]
I got the Same issue in 3.0.6 Initial Server Crash if i Drink Wine on a Server i didnt Tested it on Single player Yet it always happen after i Drink it out of the Bottle

**Comment by Mario90900** [comment]
Actually a friend of mine ran into this bug on our server, and with our testing it actually seems to be an issue with the quality being so low that it ends up trying to give you negative effects. The threshold for this is around .50 quality, and if you drink any alchohol with a quality higher then that, it dosnt kick you and you get beneficial effects. If you drink a quality of .50 or less, it seems to just crash and kick you from the server. What is interesting is that it does not seem to actually consume the item at this point, it crashes before that even happens. Something is likely bugged in Rustic's side of things, or its crashing before the onConsume stuff is completely handled. If its any help, I have the small trace of the server side of this crash, as the Client appears to be sending the server a malformed packet after drinking the alcohol.

`12.04 00:31:19 [Server] INFO {Fluid:{FluidName:"wine",Amount:1000,Tag:{Quality:0.13f}}}
12.04 00:31:21 [Server] Server thread/WARN [net.minecraft.network.NetworkSystem]: Failed to handle packet for /98.193.130.130:52379
12.04 00:31:21 [Server] INFO net.minecraft.util.ReportedException: Ticking player
12.04 00:31:21 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
12.04 00:31:21 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
12.04 00:31:21 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
12.04 00:31:21 [Server] INFO Caused by: java.util.ConcurrentModificationException
12.04 00:31:21 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_141]
12.04 00:31:21 [Server] INFO at java.util.HashMap$ValueIterator.next(HashMap.java:1466) ~[?:1.8.0_141]
12.04 00:31:21 [Server] INFO at rustic.common.blocks.fluids.ModFluids$13.affectPlayer(ModFluids.java:249) ~[ModFluids$13.class:?]
12.04 00:31:21 [Server] INFO at rustic.common.blocks.fluids.FluidBooze.onDrank(FluidBooze.java:36) ~[FluidBooze.class:?]
12.04 00:31:21 [Server] INFO at rustic.common.items.ItemFluidBottle.func_77654_b(ItemFluidBottle.java:125) ~[ItemFluidBottle.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2778) ~[vp.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125) ~[oq.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678) ~[vp.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088) ~[vp.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
12.04 00:31:21 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
12.04 00:31:21 [Server] INFO ... 9 more`

**Comment by WheresMyMtnDew** [comment]
Yes this bug just happened to me the wine was at 0.38 and it crashes me from the server. I am able to log back in will test again at purity 0.5 and see if it works okay. Also there used to be a way to empty the alcohol from the bottles by putting in a crafting grid this does not seem to be working for me either.

**Comment by EhGneissGuy** [comment]
I also encountered this bug. Crashed immediately and repeatedly. Super consistent.

**Comment by LightsDawn** [comment]
i get this crash as well but i believe its for a different reason, im thinking it tries to apply the affect to the player when there are no affects so it gives an internal server error

`05/02/2018 10:36:50
10:36:50{Fluid:{FluidName:"wildberrywine",Amount:1000,Tag:{Quality:0.48f}}}
Server thread/WARN 05/02/2018 10:36:51
10:36:51Failed to handle packet for /99.203.129.104:37684
Console 05/02/2018 10:36:51
10:36:51net.minecraft.util.ReportedException: Ticking player
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_162]
at java.util.HashMap$ValueIterator.next(HashMap.java:1471) ~[?:1.8.0_162]
at rustic.common.blocks.fluids.ModFluids$12.affectPlayer(ModFluids.java:218) ~[ModFluids$12.class:?]
at rustic.common.blocks.fluids.FluidBooze.onDrank(FluidBooze.java:36) ~[FluidBooze.class:?]
at rustic.common.items.ItemFluidBottle.func_77654_b(ItemFluidBottle.java:125) ~[ItemFluidBottle.class:?]
at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:222) ~[aip.class:?]
at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2778) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1125) ~[oq.class:?]
at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2678) ~[vp.class:?]
at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2088) ~[vp.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
... 9 more
Server thread/INFO 05/02/2018 10:36:51
10:36:51BloodNBoner lost connection: Internal server error
BloodNBoner left the game`
