### ISSUE TITLE
Bibliocraft Printing Press not working?

### ISSUE THREAD

**Issue by uglyduck2k4** [Darkosto/SevTech-Ages#1429]
## Issue / Bug

The Printing Press from Bibliocraft does not seem to be creating copies.
## Current Behavior

Currently at the moment, the Printing Press just sits there and does nothing when you add all the required materials. 
## Steps to Reproduce (for bugs)

1. added black dye
2. added plate
3. added books
4. Just sits there and does nothing. Tried added a button/switch to see if it needed a redstone signal.
5. Had other others use the printing press to replicate the same results.

## Context

Was looking for an early game of duplicating enchantments to apply to item.
Figured it was a simply way of duplicating an enchantment
## Your Environment

* Modpack Version: 3.0.4
* Java Version: 1.8.0.161(64bit)
* Launcher Used: Twitch App
* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: No

**Comment by justinrusso** [comment]
blue dye... or inc sacks?

**Comment by uglyduck2k4** [comment]
You have to use black dye, Ink Sacks can not be applied.

**Comment by ftemporini** [comment]
i can confirm that the bug persists in version 3.0.6

**Comment by Lewdicolo** [comment]
Bug still exists. Press just doesn't work. Might want to report to Mod Dev.

![image](https://user-images.githubusercontent.com/19986227/38768196-53172d52-3fb5-11e8-8cf8-bcb4db25b0a2.png)

**Comment by IChris2698I** [comment]
I'm having this issue as well in 3.0.6. I've got a stack of Black Dye Powder, an Enchanted Plate with Unbreaking III, and books. Nothing wrong with my setup as far as I can tell.

**Comment by artdude543** [comment]
After reviewing this issue and considering our options. Due to how the developer works with updates and the lack of communication on his issue tracker (could be for IRL reasons so it's not against him) we are going to disable the printing press. _(Hide and remove the recipe)_

This issue is mainly related as we don't allow Minecraft ink sak being used as a black dye. And the mod seems to not support using another dye. (Without confirming with the source code anyway)

Once the mod is updated and fixes/ resolve the issue we will re-enable the recipe for the block.

**Comment by timmit99** [comment]
Any update on this? I just removed my mending enchant from my armor in order to make a few copies and now i have no way to use the enchanted plate.

**Comment by justinrusso** [comment]
This is your update: https://github.com/Nuchaz/BiblioCraft/issues/559

Until then, the item has had its recipe removed and hidden from JEI.
