### ISSUE TITLE
[Suggestion/Experince] The Betweenlands & Weedwood Sticks

### ISSUE THREAD

**Issue by bbqx** [Darkosto/SevTech-Ages#1501]
The Betweenlands has been a really fun experience and I have been having a blast playing with it. I decided i would make an entire side base filled with farms a gadgets for the mod as a progress through it.

After finishing my fenced farm area for Mire Snails I wanted to make a safe pathway to a near by WhiteFort. However, my fun ended when I crafted my 268 or so Weedwood sticks into Weedwood Walkways. They are really cool because they give speed 2 and that makes getting around a lot safer. Sadly, I realized this was a major mistake. While it turns out that you can get the sticks from weed wood bushes, it now takes me an "unreasonable amount of time." I realized this when my last 6 hours of play had been looking for more sticks and nothing else.  Upon logging in and wanting to continue my build I suddenly realized I did not want to play with the mod again. Its just...too much.. 

## Possible Solution
I don't know, I did a search here and it seems that the sticks a set to be non renewable by choice. Its, just a really sad reason to have to pull away from the mod.

**Comment by daddy77gaming** [comment]
When playing betweenlands as a standalone i can understand not changing some configs.

If you play betweenlands in a modpack filled with loads of other mods.. changing configs and gating some stuff i think encourages use of cross mod interaction.

On this you could think about putting down totems for a speed boost along your way or wear wolf boots use slime sling etc.. thats just some examples of the long list of options.

**Comment by Ikarsu** [comment]
if we're talking about a "safe pathway", half slabs of choice and transparent blocks don't allow monsters to spawn, and for movement speed, the best solution would to wield a longsword and slime boots for some high speed. Long as you have vertical velocity and horizontal momentum, this equipment combo is the fastest way, but hardest to control to get around the betweenlands dimension (also good for water hopping). Slime Sling also works wonders if you want to launch farther than what the longsword is capable of. For my pathing, I went with betweenstone brick slabs as they output 6 and has a surprisingly good green coloring, and walled it with cobblestone walls (2 high) so those angler fish don't do their launching attack. 

You don't have to worry about lurkers as they are "neutral" to the player, just mainly have to worry about angler fish, mobs from the sludge biome, and wights due to their abilities respectively.

**Comment by markriemann** [comment]
For people that want to spend more time playing Betweenlands than bush hunting... and if you don't want to have the weedwood sticks craftable. Then make the bushes growable, aka have a sapling or something. So I'm not tracking around the swamp for 1,000+ for the closest bush.

**Comment by Vyraal1** [comment]
Going to comment on here as well from a practical point of view, while there are lightsources that do work in Betweenlands such as Astral Sorcery's Illumination Wand, there aren't many options to make simple lighting sources in BetweenLands other than Sulfur Torches (which only require Weedwood sticks). 

My group wanted to explore a lot of BetweenLands content, but it was constantly interrupted by the Weedwood Bush grind as he had to keep looking for bushes to get sticks for the BL only torches. I know it wasn't 'necessary' for pack progression to complete the BetweenLands, but something minor like the sticks was pretty offputting in trying to complete this section of the pack

And in response, to the person above, I don't think making the bush's growable is even possible from a modpack point of view, it would be much more consistent with the packs progression to make it so that weedwood planks in a BWM saw makes the sticks.

**Comment by SoundslikeLogic** [comment]
Having sticks gated feels kind of absurd in my experience. I've traveled hundreds of blocks from my spawn in Betweenlands and I still haven't found my first weedwood bush. I have not found a single stick. And now I find out they're not renewable? This isn't fun. I get that we had to work up from sticks in the Overworld, but I also worked up to the technology to cut a log down to sticks from planks. Now I'm gated extremely hard, and everywhere I go I get chased down by Wights. I don't understand and this frustration is sapping my will to play an otherwise wonderful modpack.

**Comment by Kiyaku** [comment]
Would love a way to get more weedwood sticks other than breaking bushes as well! I am planning on using betweenlands blocks for my base. Things like fences, ladders, walkways, all require sticks. Running through the dimension to punch a few bushes isn't the best experience. 

I'm trying to think of a balance reason why weedwood sticks are not craftable, but can't really think of any. Maybe cause you can make too many speed boosting paths? (if so, might as well make that recipe more expensive). 

Maybe it's not possible to separate the weedwood planks -> vanilla sticks recipe with the horsepower mod? In that case, perhaps using the BwM saw to cut down weedwood planks -> weedwood sticks would work? 

In any case, would love to see a recipe for those!

**Comment by Thiana** [comment]
[The Betweenlands v3.3.7](https://minecraft.curseforge.com/projects/angry-pixel-the-betweenlands-mod/files/2550498) makes weedwood bushes farmable.

**Comment by vadis365** [comment]
Closing as it isn't a thing in the BL anymore.
