### ISSUE TITLE
ClosedChannelException on initial load

### ISSUE THREAD

**Issue by jengeld4** [Darkosto/SevTech-Ages#1671]
## Issue / Bug

Updated from 3.0.4 to 3.0.6 and now have issue loading previous 3.0.4 saves. Initial loads of the single player save return "Internal Exception: java.nio.channels.ClosedChannelException" then send me to server select screen. Further attempts to load function properly

## Steps to Reproduce (for bugs)

1. Start save in 3.0.4
2. update straight to 3.0.6
3. Try loading previous save.

## Context

An annoyance really. Loads save fine after failing the first time. 

## Logs

* Client/Server Log: https://www.dropbox.com/sh/blstpwejab2q3za/AABtB9SBYKG4WsQ8c2_qiudQa?dl=0

## Client Information

* Modpack Version: 3.0.6 (Disabled Mo' Bends and Better Foliage due to performance issues)
* Java Version: 1.8.0.71 (64-bit)
* Launcher Used: Twitch

**Comment by justinrusso** [comment]
This is mentioned right in the changelog as a known issue

**Comment by jengeld4** [comment]
Ah, I misunderstood. I thought that meant a new save. Sorry about that.

**Comment by DragonmasterDJ** [comment]
@justinrusso this dose not seem to be the case though. I have just heard about this pack and decided to try it out. after making a world and receiving this issue I tried to rejoin it. but only for it to kick me back out with the same issue again.

**Comment by Delaterius** [comment]
@DragonmasterDJ I had the same problem. I created a second new world, and was then able to load into either.

**Comment by justinrusso** [comment]
This appears to be fine. No one has been finding issues since this change.

**Comment by Logins555** [comment]
I been having the same error mesage almost every time I attempt traveling between dimensions:

Connection Lost
Internal Exception: java.nio.channels.ClosedChannelException

Then got kick out to the server select screen, and then sometimes when opening the save find my character teleported a bit more than 1100 blooks away and often inside of a moutain... 

    Modpack Version: 3.0.7 (Disabled Better Foliage, Fancy Block Particles and Smooth Font due to performance issues, added AromaBackup)
    Java Version: 1.8.0.71 (64-bit)
    Launcher Used: Jar launcher on Twitch.

Log:
https://www.dropbox.com/s/n3z12fephc5esys/latest.log?dl=0

**Comment by KS-HTK** [comment]
This Bug is not fixed. I have been having this Issue since 3.0.2(when I started playing) and I still get it. Currently on 3.0.8

**Comment by DaDiamondDragon** [comment]
I am on 3.0.8 and I am still experiencing this problem. When initially loading up the pack, I am able to join my world just fine, but if I left the world and tried to rejoin after playing for a while, it would close the world, reading: Shutting down internal server, and then give the ClosedChannel Exception. I would try again and again to rejoin, but the same issue repeated. This would be fixed by closing the whole pack and then reopening it, so if it were just that it would be a minor inconvenience. However, the issue also occurs on some occasions when I am going between dimensions. When going to the Betweenlands, the issue would occur and when I finally managed to get back into the world, I would find myself hundreds of blocks away from my portal and in a cave. So far, this issue has occurred going to and from the Betweenlands, Nether, and Hunting Dimension, but never the Twilight. I have found myself teleported to locations such as in caves, suffocating in stone in a mountain, and in a lava lake. All of this is very frustrating and wastes a ton of time, because it takes the pack 10 minutes to load for me, even with 8 GB of RAM allocated.
