### ISSUE TITLE
Severe Delay when opening GUIs

### ISSUE THREAD

**Issue by Andyghandi** [Darkosto/SevTech-Ages#1675]
When opening any gui, like crafting table, strainer gui, chest gui etc, the game freezes for a period of time before it stabilizes again. It starts around 0.5 seconds when first playing and increases badly up to 3 seconds after a bit of gameplay. This is very annoying, especially in age zero where opening gui's are happening all the time.

**Comment by PaladinWho** [comment]
I have had this problem before.  It is likely due to some issue with NEI, I'm really not sure what causes it and it seems to affect people at random.  How I fixed it:  Go into inventory, click settings on bottom left, click top NEI settings button, disable NEI.  Keep in mind, f3 is not available and NEI is what allows f7 and f9 so lighting and prospecting will be difficult without light levels or chunk borders.

**Comment by Andyghandi** [comment]
**Client Information**
Modpack Version: Latest (3.0.6)
Java Version: Latest (Java 8 161)
Resource Pack: Yes R3Dcraft 64x
Launcher: Twitch launcher with forge 14.23.2.2651
Additional mods: No

**Comment by Andyghandi** [comment]
As of now, disabling NEI fixes this issue, but this is something I would consider worth overlooking as it affects gameplay drasticly. Thanks for your input Paladin.

**Comment by maverag** [comment]
also encountered and nei is disabled only jei is enabled.

**Comment by Wipperwill** [comment]
I also have this problem. Sometimes I can restart and clear it but most time i get some sort of lag as described above, .5 to 3seconds lag. Disabling NEI fixes it.

Minecraft up to date
Java up to date,
Latest version of Sevtech
10Gig allocated for game using twitch launcher.
Windows 10, 64bit

**Comment by vadis365** [comment]
duplicates #778
