### ISSUE TITLE
Can't start the server

### ISSUE THREAD

**Issue by TripleZ0** [Darkosto/SevTech-Ages#1684]
## Issue / Bug

Can't start the server. It crashes almost immediately.

## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log: https://pastebin.com/kG5Nz5Nt
* Crash Log:

## Server Information
* Java Version: 1.8.0_162
* Operating System: Debian Stretch
* Hoster/Hosting Soultion: Home
* Sponge (Non-Vanilla Forge) Server?: Default

* Additional Content Installed?: None

**Comment by SteseDav** [comment]
Is this running as a dedicated server? If so, ensure you've run the setup/install.sh files, and changed the EULA file value from 'false' to 'true'

**Comment by TripleZ0** [comment]
This is running on my home server. I ran the install.sh file. I tried to run it with the StartServer.sh and tried it with a simple "java -jar xxx.jar" command.

**Comment by SteseDav** [comment]
did you do the EULA file? (i've tripped over this a few times)

**Comment by TripleZ0** [comment]
Yes, I did. I moved the whole thing to my laptop. I was able to start it there.
What could be the issue?

**Comment by SteseDav** [comment]
When you ran the java command, did you run it with root/sudo privs?

**Comment by TripleZ0** [comment]
I run it under root. I tried it to run under user but got the same problem.
I will try to reinstall the modpack under root.

**Comment by SteseDav** [comment]
You'll probably find this 'issue' gets closed, as its not down to the pack itself... I've personally not got any other ideas that may assist.

**Comment by marlburg** [comment]
did you chmod +x Install.sh and StartServer.sh the files?

**Comment by artdude543** [comment]
On the Java command ensure you have `nogui` on the end as you don't need it tbh. Also, it seems your install is corrupt either in Java or the Server Install. So please perform a re-install of Java and re-download the Forge/Minecraft/Libs files needed for the server.

On the server download we provide we use the following

`java -server -Xms${MIN_RAM} -Xmx${MAX_RAM} ${JAVA_PARAMETERS} -jar ${SERVER_JAR} nogui`

Which works correctly if Java is installed correctly and the latest 8 build. Otherwise this is user error and after the steps mentioned above I don't have any other suggestions as you've already tried permissions etc.. 

`java.io.IOException: Resource temporarily unavailable` is also relaable to too many processes running on an instance and/or not enough free memory for the JVM to use. So ensure you have enough valid **free** memory for the JVM to allocate to it's self as is provisions it and will hog all you tell it to use.
