### ISSUE TITLE
Error with sevtech server

### ISSUE THREAD

**Issue by Occuvite** [Darkosto/SevTech-Ages#1698]
[logs.zip](https://github.com/Darkosto/SevTech-Ages/files/1895673/logs.zip)

I have problem with sevtech server.
Hosting https://www.myarena.ru/home.php?m=gamemanager&p=ftp&home=6555
4gb-10gb RAR

**Comment by sarcastic6** [comment]
```
[20:19:20] [main/ERROR] [FML]: Unable to read the jar file CraftStudio-1.0.0.93-mc1.12-alpha.jar - ignoring
java.util.zip.ZipException: error in opening zip file

[20:19:20] [main/ERROR] [FML]: Unable to read the jar file modtweaker-4.0.9.jar - ignoring
java.util.zip.ZipException: error in opening zip file

[20:19:20] [main/ERROR] [FML]: Unable to read the jar file supersoundmuffler-1.12.1-1.0.2.9.jar - ignoring
java.util.zip.ZipException: error in opening zip file
```

Your files appear to be corrupt.  Try re-downloading the pack and uploading it to your server again.

**Comment by Occuvite** [comment]
Now i have this problem 
[log.zip](https://github.com/Darkosto/SevTech-Ages/files/1895832/log.zip)

**Comment by artdude543** [comment]
All your files are corrupt re-upload **all** files and try again. Before doing so delete both the mods and config folder. This will solve your issue. Otherwise your FTP transfer to the server is broken and is breaking files.

This is a not a pack issue and a user/host error. So if the issue persist with the zip file opening error. Please consult with your hosting provider.
