### ISSUE TITLE
Client Crash on Entering Betweenlands

### ISSUE THREAD

**Issue by Petapaka** [Darkosto/SevTech-Ages#1739]
## Issue / Bug
Started a portal to the Betweenlands on a server world, tried to enter and crashed my client.
I tried restarting the server, client computer, and a clean install of 3.0.6. Also tried copying the world to a singleplayer and entering that way, same happens.

I think the issue might be a geo

Copied 'latest.log' to a gist here:
[https://gist.github.com/Petapaka/3618343f8e27c7e9b25516bc4cc8efdd](https://gist.github.com/Petapaka/3618343f8e27c7e9b25516bc4cc8efdd)

## Expected Behavior
Able to re-enter the world after client crash.

## Possible Solution
Issue with geolosys causing cascading worldgen lag? Saw that, but not sure it's the cause. Makes sense if I was trying to generate the new dimension at the time of crash, and each time I tried to reenter the world.

## Steps to Reproduce (for bugs)

1. Set up a portal to between lands.
2. Enter portal.
3. Client crash.
4. Try to re-enter world, client crash.

## Context
I can't re-enter the world I was working on.

## Logs

* Client/Server Log: [https://gist.github.com/Petapaka/3618343f8e27c7e9b25516bc4cc8efdd](https://gist.github.com/Petapaka/3618343f8e27c7e9b25516bc4cc8efdd)
* Crash Log: Couldn't find a log specifically named 'crash-log', could it be named hs_err_pid8932.log?

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8 161
* Launcher Used: Twitch

* Memory Allocated: 6144 Mb

* Server/LAN/Single Player: Server
* Resourcepack Enabled?: No
* Optifine Installed?: Yes, 1.12.2 HD U D1

**Comment by Jandakast** [comment]
Yes we will need the hs_err_pidXXXX.log file. I've seen something like this in the past and it ended up being Nvidia drivers needing to be updated/clean reinstalled. The hs_err_pidXXXX.log file may contain IP addresses. So you might want to sanitize/remove those before posting. 

I would also try removing Optifine and seeing if you still have the issue.

**Comment by Petapaka** [comment]
[https://gist.github.com/Petapaka/5e7edf426a223dc49a03d25df3be07e0](Here's the hs_err_pidXXXX.log file.)

I'm reloading without Optifine now. That would be a nice easy fix.

**Comment by Petapaka** [comment]
No luck on the server side without Optifine. Trying the singleplayer copy now.

**Comment by Petapaka** [comment]
No luck. Hopefully the answer is in the log files. :/

**Comment by Petapaka** [comment]
Started a new world in creative, created a portal to the betweenlands, entered it, and my client crashed. Must be an issue with my computer or drivers or setup, right?

**Comment by Jandakast** [comment]
The error log shows the problem is ig7icd64.dll which is the Intel Graphics driver. Update your graphics drivers. Also shows that you are running Java 1.8.0_25. Update Java to at least Java 1.8.0_161. If using the Native Launcher you have to change the Java version every time you launch the pack from within the Native Launcher. Or you can go into your Twitch app settings and change to the Jar Launcher and set it to always use latest. You may need to accept a pop up asking if you want to reset settings and then relaunch the Twitch App before you can launch the pack again.  

Based on the information in the log it looks like you may have an NVidia card. If so; 

1. Nvidia Control Panel
2. Manage 3D settings
3. Program Settings
4. Add
5. Browse
6. C:\Program Files\Java\jre1.8.0_161\bin\javaw.exe (Replace with path to the newest Java you have installed)
7. Choose "High-Performance NVIDIA processor" in the Drop down
8. Apply
