### ISSUE TITLE
Spongeforge not working correctly.

### ISSUE THREAD

**Issue by Artitus** [Darkosto/SevTech-Ages#1741]
## Issue / Bug

When I start my server with SpongeForge installed I get this:

http://p.artit.us/apocinacaj.prolog

Now I understand that the most obvious thing is that sponge isn't compatible, and to that I say: No shit.

How then are the other servers doing so? No way they have devs good enough to fork sponge and make it work. Is there a lower version of forge I can use to make sponge work? I'm a quite seasoned system admin and server owner.

## Logs

* Client/Server Log: http://p.artit.us/apocinacaj.prolog

## Server Information
* Java Version: 8
* Operating System: Ubuntu 16.04
* Hoster/Hosting Soultion: AWS EC2
* Sponge (Non-Vanilla Forge) Server?: Trying to make it this.

* Additional Content Installed?:

**Comment by Jandakast** [comment]
Looking at your log the last thing it is trying to do is load Better FPS before shutting down.

If I remember correctly Better FPS and Foam Fix have to be removed in order to get it to even launch. However, even if you get it working with Sponge you will have issues with some scripts and mod interactions. For example Villager Trades are completely broken when using Sponge.

I recommend not using Sponge, at all! This isn't a pack issue.

**Comment by leelawd** [comment]
Just as a note to @MissPotato We run this pack perfectly fine using SpongeForge (Besides the few hickups with advancments and such) and we are a medium population bukkit-esque community. @Artitus the issue is you are running a higher Forge version than SpongeForge is compatible with, AFAIK they are currently in the process of updating due to these errors and mods using higher versions. 

You can get the correct forge for sponge over at https://files.minecraftforge.net/
