### ISSUE TITLE
Problem with jei when i use sponge for hexacord and map broken

### ISSUE THREAD

**Issue by MrHoStille** [Darkosto/SevTech-Ages#1759]
I have a problem with jei, when I connect to the hub with PaperSpigot and then switch to modpack with Sponge the available items are broken.

There are only liquids that are available at the higher stages that are displayed, the bug comes from modpack, sponge, or hexacord?

The map is also broken when I use sponge, it creates biomes squares.

Sorry for my english, im french.

**Comment by artdude543** [comment]
You're using an unsupported server version I.E. Sponge. We don't offer support **at all** for Non-Vanilla Forge servers. Due to Sponge/Bukkit etc.. known to break Forge itself along with Vanilla mechanics. If you can reproduce the issue in a Vanilla Forge environment then please open another issue.

Otherwise sadly as your using Sponge, we can't help you.

**Comment by MrHoStille** [comment]
Sponge is obligatorily forge for modpack, why do you say that I use sponge vanilla?

**Comment by artdude543** [comment]
Sponge is not "obligatorily" it's a waste of space and time in my opinion. You stated that your using "PaperSpigot" which is built on Spigot which is another issue in the world of modpacks. 

You're using a server which is not **Vanilla Forge** which is the **only** server we support for pack support. I'm telling you that if you wanted your issue to be looked into more you'll need to re-create the issue in a Vanilla Enviroement with no Sponge/Spigot etc... just Forge and that's all.
