### ISSUE TITLE
Redwoods cost too much

### ISSUE THREAD

**Issue by Habeeb-M** [Darkosto/SevTech-Ages#1933]
Redwood saplings require 1 gold each, which is very very expensive, considering one redwood tree takes a 7x7 square, which means **one** redwood tree takes 49 gold. That's a ridiculous amount.

Although looking at it, one redwood tree gives many stacks of wood planks, but still, 49 gold is way to overpowered. Something like 8 or 16 would be better.

**Comment by artdude543** [comment]
I feel the cost is fine, to be honest. As they are disabled by default anyway due to the issue that tree can cause in the world. That trade in the market is default in the blockheads mod anyway. I don't believe that us changing it will make anything better. If anything if we have the generation disabled the trade should be removed.

But if you wanting to slash out your gold for the tree then I think that you should pay up for it; we have it off for many reasons so I'm going to look at this as a trade-off cost if you want one in your world.
