### ISSUE TITLE
Incorrect world gen on locally hosted server

### ISSUE THREAD

**Issue by Iri5hman** [Darkosto/SevTech-Ages#1970]
During world generation on a locally hosted server the world is generated incorrectly, and as if it is a vanilla world, the grass doesn't drop plant fiber and only drops seeds, there are no modded items to be seen anywhere, there are also no advancements available. NEI shows all mods loaded from what i can tell. Also together forever isnt even loaded and no commands come up for it.

 
## Issue / Bug
-Incorrect world gen
-No advancements
-together forever not seemed to be loaded

## Expected Behavior
when starting a world i expect a normal sevtech generation, but instead it generates like a vanilla world with no advancements.

## Possible Solution
I could be i dont know how to use the server but simply adding more documentation would be cool.

## Steps to Reproduce (for bugs)

1. Double click forge installer
2. Double click forge.jar
3. Double click start.jar (the program runs then immediately closes)
4. Double click server.jar
5. World gens and it ends up as vanilla world gen

## Context
I was trying to create a locally hosted server to play with a few people and i was getting these isuues that disallowed me to do that.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information
most recent versions of everything as of 4/18

* Memory Allocated: client: 4gb  server: Default(512 MB?)

* Server/LAN/Single Player: server
* Resourcepack Enabled?: no
* Optifine Installed?: no

## Server Information
* Java Version:
* Operating System: windows 10
* Hoster/Hosting Soultion: Locally hosted server
* Sponge (Non-Vanilla Forge) Server?: Using only sevtech's server package

* Additional Content Installed?:

**Comment by Iri5hman** [comment]
> If you go to: https://minecraft.curseforge.com/projects/sevtech-ages/files and download the server file, there is documentation on how to setup a server.
I followed the documentation inside the server download, this is where i got to.

**Comment by sidshep** [comment]
This is the case with mine too. I start the server and its the same with no advancements and cant pick up stuff but the JEI is full unlocked.

**Comment by justinrusso** [comment]
Can you upload your crafttweaker.log file to something like gist.github.com

**Comment by Iri5hman** [comment]
> Can you upload your crafttweaker.log file to something like https://gist.github.com

[https://gist.github.com/Iri5hman/e7f1d8c971e61611f477b0e69c9747ef](Here) is the gist of the crafttweaker file

**Comment by artdude543** [comment]
One thing which is throwing signs at me that you have a broken install or it's installed wrong that commands are not showing/working for you. As they **will work** if the server is setup correctly.

The server files are rigorously tested before being uploaded, to ensure that worlds/mods are loading as intended. Also `most recent of 4/18` is not helpful either please give us the versions. I'm going to assume 3.0.6 anyway but that's not the point of the template asking for the version.

This version _(server wise)_ was tested more than any other version. So I know **100%** that the installer/setup works absolutely fine with no issues.

I also recomend using the Scripts to install/start the server also as we add additional parmeters to the startup which helps with server performance. Also running Forge Servers via "double clicking the jar" is not ideal as it boots the GUI which decreases overall performace. You don't need a GUI for a server setup.

All I can recomend is deletiung all the files, grab a fresh download use the scripts provided to install/start  the server and then try again. _(Also make sure you joining the server with a SevTech Client and not vanilla, as I had this issue with another user (don't ask how they did not notice but it's known that people miss it))_

If you still encouter issues with the server then there is nothing much we can do to help as the server download works out of the box. Of which the majoroty of peopl who use the download don't face any issues only teething issues such as memory or saving issues (but that's another story)

Hopefully this helps you; but from what I can tell from the information given the server is running as Vanilla.

Main note here is `4. Double click server.jar` which sounds like your loading the `minecraft_server...jar` file which is wrong (that's the vanilla files needed for Forge) you would double click the forge.jar (but don't do that use the start script, that's why we provide it)

**Comment by Iri5hman** [comment]
> One thing which is throwing signs at me that you have a broken install or it's installed wrong that commands are not showing/working for you. As they will work if the server is setup correctly.

The server files are rigorously tested before being uploaded, to ensure that worlds/mods are loading as intended. Also most recent of 4/18 is not helpful either please give us the versions. I'm going to assume 3.0.6 anyway but that's not the point of the template asking for the version.

This version (server wise) was tested more than any other version. So I know 100% that the installer/setup works absolutely fine with no issues.

I also recomend using the Scripts to install/start the server also as we add additional parmeters to the startup which helps with server performance. Also running Forge Servers via "double clicking the jar" is not ideal as it boots the GUI which decreases overall performace. You don't need a GUI for a server setup.

All I can recomend is deletiung all the files, grab a fresh download use the scripts provided to install/start the server and then try again. (Also make sure you joining the server with a SevTech Client and not vanilla, as I had this issue with another user (don't ask how they did not notice but it's known that people miss it))

If you still encouter issues with the server then there is nothing much we can do to help as the server download works out of the box. Of which the majoroty of peopl who use the download don't face any issues only teething issues such as memory or saving issues (but that's another story)

Hopefully this helps you; but from what I can tell from the information given the server is running as Vanilla.

Main note here is 4. Double click server.jar which sounds like your loading the minecraft_server...jar file which is wrong (that's the vanilla files needed for Forge) you would double click the forge.jar (but don't do that use the start script, that's why we provide it)

Ok, thanks this helped alot, i needed to run the startserver.bat several times before it didn't just close out on me, that was my issue, i didn't really have much feedback from my system on weather or not it was working. it works now though so all is well

**Comment by artdude543** [comment]
Sorted! Glad you got it working :)
