### ISSUE TITLE
Won`t launch the modpack

### ISSUE THREAD

**Issue by Colocia** [Darkosto/SevTech-Ages#2009]
After I updated to 3.0.6 the launcher won`t work. it sayes: The version you are trying to play inherits properties from an unknown version. I have looked on the internet and found some solutions but it only works the one time I launch the game. if I log out and try to launch it again the same thing pops up.

**Comment by artdude543** [comment]
You need to follow the template to get support period. (It's really easy to follow and understand) 

This is not a pack issue either. But sounds like your install is broken. Reinstall the entire profile on Twitch and try again if not you'll need to re-install the Minecraft mod for the launcher. You can Google on how to do this; otherwise, you'll need to contact the launcher support team for further help.

Any further issues w/o the template will be closed and ignored.
