### ISSUE TITLE
Unidentified Version

### ISSUE THREAD

**Issue by BlueP1ckles** [Darkosto/SevTech-Ages#2012]
## Issue / Bug

Cannot install the modpack. https://gyazo.com/c1a991d2b7fb09fb54e8a29031748331
## Expected Behavior

Installing the mod pack
## Possible Solution

Uninstalling and reinstalling the launcher (attempted)
## Steps to Reproduce (for bugs)

1. Install twitch
2. Attempt to install sevtech

## Context

I can't play the modpack
## Logs

* Client/Server Log:
* Crash Log:
Can't show log as I never even got to install the game.
## Client Information

* Modpack Version:14.23.2.2651
* Java Version: 1.12.2
* Launcher Used: Twitch launcher
 folder doesn't exist
* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by artdude543** [comment]
Your Minecraft Installation on Twitch is broken. Use the repair option under the `...` for the SevTech page/view for the launcher to re-setup the MC side. Otherwise, you could try using the Jar launcher which you can enable via the settings. As this is not a modpack issue if you get further issues with launching.

You can get support via Twitch using the launcher help section or Google.

**Comment by BlueP1ckles** [comment]
Tried that. Same issue happened, (repairing)

**Comment by BlueP1ckles** [comment]
Also google had nothing, so yeah.
