### ISSUE TITLE
Crash on entering world related to Pneumaticraft Spawner Agitator

### ISSUE THREAD

**Issue by DerpityDoo** [Darkosto/SevTech-Ages#2029]
## Issue / Bug
I was in the overworld when I first crashed, the agitator'd spawners are all in the nether, there are 3 stacked on top of eachother

## Possible Solution
???

## Logs
https://pastebin.com/iHd5ywvE

## Client Information

* Modpack Version: 3.0.6
* Java Version: jdk1.8.0_144
* Launcher Used: Twitch

* Memory Allocated: 12G

**Comment by desht** [comment]
Looks like the issue is Despawning Spawners playing particle effects which the server tries to send to the Spawner Agitator fake player, which doesn't have an initialised network connection, thus crashes.

Short-term workaround: disable Despawning Spawners particle playing (**B:displaySpawnerParticle**).

I have what I believe will be a long-term fix available in builds 177+ from http://jenkins.k-4u.nl/job/PneumaticCraft-Repressurized/.  Hard to be 100% sure since I can't reproduce the problem in my dev instance, but I'm pretty confident this will resolve the problem.  Some feedback on the above dev build would be appreciated - we'll get a hotfix release out based on this ASAP if it solves the problem.

**Comment by DerpityDoo** [comment]
Your short-term fix worked great, and now that I have loaded in the crash is no longer happening after reenabling Spawner Particles, so, unfortunately, I cannot test your latest build to see if it fixes the problem. If it happens again I will be happy to test it out. Thanks for the help!

**Comment by MrHrulgin** [comment]
@desht Upgrading past build 177 did indeed fix this crash. Thank you.
