### ISSUE TITLE
Improved Backpacks Issue on log in.

### ISSUE THREAD

**Issue by SphynxLoL** [Darkosto/SevTech-Ages#2049]
## Issue / Bug
Upon logging in today (single player world), I went to open my _Improved Backpacks_ backpack and got the 'drop unfamiliar item' dialog. The item was missing from my hotbar and nowhere on the ground to be found. This might be related to the Closes Channel Exception as well. Since everytime I log in, it boots me for the first time. I'm assuming it dropped the backpack when I first logged in, the 'internal server shut down' my backpack despawned. 

I have dropped a backpack before due to a random "unfamliar" dialog. Luckily I was able to pick it up then. Unfortunately, not this time.

## Expected Behavior
I'm in the creative age. I shouldn't be dropping items due to "unfamiliarity". Wouldn't be a problem if I could just pick the backpack up again but it was completely missing.

## Possible Solution
Not sure of the order in which a players ages/advancements are checked up logging in. I'm guessing the "advancement check" didn't happen fully before I was completely logged in. Forcing me to drop the backpack. 

## Steps to Reproduce (for bugs)

Not Reproducable seems random
1. Age: Creative
2. Improved Backpacks Fully Upgraded Pack in hotbar (slot 8)
3. Log into singleplayer world. 
4. Closed Channel Exception - Sent to server list.
5. Log back in.
6. Backpack missing from hotbar and nowhere to be found on the floor.

## Context

Well. I lost pretty much all of my wrenches, tools, and a lot of other expensive items/materiels stored in the backpack.

I did also have 2 Iron Backpacks nested in the Improved Backpack. Not sure if something went weird there.

## Logs
Providing Latest Log as there was no crash.
Latest.log: https://gist.github.com/SphynxLoL/9856322cc740a39b337ff645cd467921

## Client Information

* Modpack Version: 3.0.6
* Java Version: jre1.8.0_162
* Launcher Used: Twitch Launcher (Jar Launcher Option)

* Memory Allocated: 4gb

* Server/LAN/Single Player: Single Player
* Resourcepack Enabled?: No
* Optifine Installed?: Yes

**Comment by artdude543** [comment]
Sadly this is an issue a lot of people are having with the whole timeout issue (which is mostly/fully fixed in the upcoming update) but due to how the network pipeline works and the syncing, you'll likely drop items due to "not knowing" what they are while things are still ticking over.

I've never encountered people losing things all together tho (but we don't have any mods which can remove things from the world anyway) so I'm sorry to hear about you losing your items/goods. Normally I see peoples stuff being thrown quite a way (for no reason) and generally, it's found on top of something or hidden under slabs. I'm going to consider the issue fixed in 3.0.7 and link to the issue in regards to #1671 

Again sorry about you losing your stuff, this issue with timeout has plagued the pack for a while now and hopefully it will long in the past come 3.0.7 😄
