### ISSUE TITLE
Crash after returning from the beneath dimension to the overworld

### ISSUE THREAD

**Issue by Tophenator** [Darkosto/SevTech-Ages#2060]
Title says it all. I can go to the beneath dimension just fine, but when I right click on the block to return to the overworld I fall through the world like I am in spectator mode. Then I can run through the wall to land in a cavern below. After that happens my game crashes with this error "The game crashed whilst ticking entity Error: java.util.NoSuchElementException"

Update - 3.0.6
Using Twitch launcher
Optifine - Yes

Here is the crash log. Plz help.

[crash-2018-04-24_16.39.12-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1944547/crash-2018-04-24_16.39.12-client.txt)

TLDR: READ THE TITLE

**Comment by Jandakast** [comment]
This looks to be an issue with Antique Atlas trying to query the biome IDs to update your map. Since I cannot reproduce the crash I cannot work with the devs if they need more information. Try removing Optifine to see if the crash still occurs. If it does please report this to the Antique Atlas devs. 

If removing Optifine fixes the issue then you can try removing the Atlas from your hotbar before switching dimensions.

**Comment by Tophenator** [comment]
Java just released an update. I updated it and the problem seems to work. Ill close it for now but if it occurs again I will reopen it. Thanks Jandakast
