### ISSUE TITLE
Renderer issue after restarting Minecraft

### ISSUE THREAD

**Issue by mymiya** [Darkosto/SevTech-Ages#2061]
## Issue / Bug

After a few days, my render goes crazy. Can play for hours and hours, but only after restarting minecraft a few times, I cant play anymore from the renderer going crazy, and when I move, the camera flies into the sky. I have a gif of the behavior I'm mentioning. The only thing I can do to fix it is reinstall the pack and move the save folder over.

https://gph.is/2HVi0qM

## Expected Behavior

This not happen when I restart minecraft
## Steps to Reproduce (for bugs)

1.
2.

## Context

Just trying to play the modpack the next day, and can't

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: 3.0.6
* Java Version:  
* Launcher Used: 

* Memory Allocated: 6144MB

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?: Yes, but have taken it out, and it made no difference.

**Comment by Jandakast** [comment]
I don't think this is anything we can fix. Things like this are usually caused by some sort of file corruption or out dated drivers. If a fresh install fixes the issue for a couple pack restarts then it likely isn't out dated drivers and is instead corruption of something within that pack. I would suggest trying to not using Optifine for a couple days and see if still happens. You could also try white listing your minecraft instance folder from active scans in your antivirus software.
