### ISSUE TITLE
Entitie's textures weird bug

### ISSUE THREAD

**Issue by FurryKitten** [Darkosto/SevTech-Ages#2088]
## Issue / Bug
All items and entities textures started floating in the air after I reached age 3 and entered Nether (but Im not sure that problem appeared after this). While textures are floating, my fps is around 10-20 (normally it was 100-120). That issue appears on my server, and client is fine, because my friends have the same issue only on server.

Screenshots:
https://imgur.com/a/4W3lPYv

## Context
I tried different algorithms in BetterFPS, but that doesn't helped. 

## Logs
Server Log: https://gist.github.com/FurryKitten/e7c9902535a616cf855373f36a3bb596
Client log: https://gist.github.com/FurryKitten/3b279f0d57aa8bbd9da84148bf81fea1

## Client Information
* Modpack Version: 3.0.6
* Java Version: 8 upd 171
* Launcher Used: ATLauncher
* Memory Allocated: 6gb
No optifine, standart resource pack.

Server
* Java Version: 1.8.0_141
* Operating System: Debian 4.9.30-2
* Hoster/Hosting Soultion: OVH Dedicated
* Sponge (Non-Vanilla Forge) Server?: No
* Additional Content Installed?: No

**Comment by artdude543** [comment]
Try removing BetterFPS and/or installing Optifine to the pack. Seems like your PC is having some issues handling the rendering. But this is not a pack issue but a client-side issue. You could also try tweaking some Java Args we [recommend these](https://pastebin.com/hWWUGGHQ).

If they do not help then that's about as far as support we can offer due to this being something with your PC setup. Your on a good version of Java, but I guess make sure your Graphic Drives are up to date.

This pack is very demanding and is not ideal on low end spec machines (or integrated graphics) but I've mentioned what stuff you can try to help you out 😄
