### ISSUE TITLE
Betweenlands composting not working as intended

### ISSUE THREAD

**Issue by tyranno66** [Darkosto/SevTech-Ages#2129]
**Issue / Bug**
  All compostable items in betweenlands give one compost item.
**Expected Behavior**
  The betweenlands wiki itself says that different items should yield different amounts of compost. This is also noted in JEI.
**Possible Solution**
 Check if anything's going on with the compost recipes?
**Steps to Reproduce**
  1. Get a betweenlands plant item that is compostable.
  2. Compost it in the compost bin.

Modpack version: 3.0.6

**Comment by Rixxaw** [comment]
This is a Between lands issue go report it there!  Why do you need so much composted items?  ITs literally a trashcan system to get rid of stuff ??!?!?!1?!

**Comment by Rixxaw** [comment]
And I feel issues like this keep Real issues from being addressed, which is why I'm a little snarky.

**Comment by LycanBlackpaw** [comment]
@Rixxaw You do know that it is, by far, *not* a trashcan, correct? The Betweenlands compost bin is a vital part of Betweenlands farming. You literally cannot-I repeat, you *CAN NOT* farm without compost in the Betweenlands. So this bug, while probably being a Betweenlands bug and not a pack bug (testing it by placing the mod in a Forge instance on it's own would determine this) is very bad for farming any and all Betweenlands crops and materials.

**Comment by LycanBlackpaw** [comment]
@Rixxaw Nice ninja edit for removing your hate speech. However, as it is quite unnecessary to be hateful in general for any reason, I have reported you. Thank you for your unneeded input, and have a nice day!

**Comment by Rixxaw** [comment]
I don't hate you man... Just look at how many issues there are I simply edited it to reduce the amount of reading required.  I think hate speech is a little strong.  Frustration with someone who is being persistent to clog up a busy issue tracker is more accurate.

**Comment by Rixxaw** [comment]
There you go @LycanBlackpaw you also have been reported.  Have a nice day :+1:

**Comment by EhGneissGuy** [comment]
@tyrano66 I was starting to think I was crazy. Thanks for sharing.

**Comment by vadis365** [comment]
The original issue will be looked in to thanks for the report.
The rest of the comments are just snarky to each other and a complete waste of everyone's time.
Please keep it civil. A lack of understanding does not excuse rude behavior - I am connected with both the SevTech pack and the Betweenlands mods and as such read these issues several times a day, as far as 'dogging up' the issue tracker goes, that is none of your concern as it allows messages to be relayed to me and by proxy the BL team with regards to the the function of the mod in SevTech.
Closing due to annoyance - thank you @tyranno66 - we will look in to the issue at the mod side.
