### ISSUE TITLE
Piranha spawns every few min near river

### ISSUE THREAD

**Issue by WheresMyMtnDew** [Darkosto/SevTech-Ages#2140]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version: Current
* Java Version: 
* Launcher Used:
6g

**Comment by vadis365** [comment]
Seeing as this only has a title and no actual issue - I'm guessing it's a complaint rather than a real issue.
The spawning is fine for the pack and has been worked on to be optimal for various mobs, the fish are fine.
If however the "Piranha spawns every few min near river" title means that fish are not spawning IN the river and are spawning in areas NEAR the river, I would hazard a guess that that isn't happening. The fish can only spawn IN water, therefore I am closing because his is a comment and not a genuine issue.

**Comment by WheresMyMtnDew** [comment]
Sorry I was trying to ask a question

**Comment by vadis365** [comment]
The fish will spawn in any biome considered water, including rivers, oceans and swamps.

**Comment by WheresMyMtnDew** [comment]
No I understand that but what I am asking is since when have they spawned every min or so in the same chunk of river?

**Comment by vadis365** [comment]
Then re-locate if it's a particularly bad place to build?
