### ISSUE TITLE
Suggestion: Alias "Limestone (raw)" with "Limestone (Betweenlands)"

### ISSUE THREAD

**Issue by Sorbe** [Darkosto/SevTech-Ages#2196]
## Issue / Bug
Limestone (raw) is separate from Limestone (Betweenlands).

## Expected Behavior
I was wanted to make some Limestone Stairs and Walls, but they are not craftable if you only have raw.
This is issue to the Marble (raw) and Marble (Astral Sorcery) non-aliased issue, which is also confusing.

## Possible Solution
Maybe oredict alias the two limestones and potentially remove one.

## Context
It means that I have lots of overworld Limestone that is going unused.

## Client Information
Sevtech 3.0.6
Java 8u181
Jar Launcher
8GB Java VM
Client/Server
Soartex
No Optifine

**Comment by Jandakast** [comment]
The different limestone and marble types are needed for specific recipes/structures within their respective mods. You can chisel the Limestone and Marble to any of the different types to use in the recipes. 
Adding The Betweenlands Limestone to the oreDict will also require some recipe reworks for The Betweenlands recipes in order to make the recipes use the oreDict.

I personally don't think this is necessary as you can just chisel them to whatever type you need.

**Comment by justinrusso** [comment]
I think this can safely be ore-dicted.. The recipes would just need to specify the item specifically rather than an oredict, which it currently does.

**Comment by justinrusso** [comment]
Now that I understand the request more, I'm going to disagree with this suggestion. I think it makes sense to have to use the specific type as it looks different compared to the other limestone. You can convert between them with a chisel if you really desire.

I do think though that they should be oredicted for the sake of a slight enhancement in any recipes that use limestone in general.

**Comment by Jandakast** [comment]
We will not be changing the recipes that aren't already using the oredict but The Betweenlands limestone has been added the blocks to oredict for 3.0.7
