### ISSUE TITLE
Free Range Hawks Advancement Not Working

### ISSUE THREAD

**Issue by CrossMyDNA** [Darkosto/SevTech-Ages#22]
I crafted a tomahawk, but the advancement still says 1/2, and won't complete even after crafting/using multiple tomahawks.

**Comment by Dawenzel** [comment]
I believe it's not working because the criteria for the advancement is triumph:player_crafted_item which doesn't work with the crafting stump. It would work if the criteria were minecraft:inventory_changed like is used with the gear advancement or make the recipe shapeless and craftable in the 2x2 crafting grid.

**Comment by Darkosto** [comment]
Added as a pickup advancement instead of crafting one, should alleviate the problem for everyone!
