### ISSUE TITLE
shift clicking does not work (wooden basins, grills etc. don't give the items back when shift-clicking)

### ISSUE THREAD

**Issue by tkkot** [Darkosto/SevTech-Ages#2201]
## Steps to Reproduce (for bugs)

1.
2.

## Logs

* Client/Server Log:
* Crash Log:

## Client Information

* Modpack Version:
* Java Version:
* Launcher Used:

* Memory Allocated:

* Server/LAN/Single Player:
* Resourcepack Enabled?:
* Optifine Installed?:

## Server Information
* Java Version:
* Operating System:
* Hoster/Hosting Soultion:
* Sponge (Non-Vanilla Forge) Server?:

* Additional Content Installed?:

**Comment by Brettflan** [comment]
Also, note that you cannot have anything in your off-hand (shield or whatever) if you're trying to pick up the block types that support it.

**Comment by artdude543** [comment]
One you did not fill any information in. So congrats on making a useless issue. Also, you need to have an empty hand when sneaking to get the items out. This is the intended method for the mods. You're clearly doing it wrong to _not_ been getting items out.

Next time you post an issue fill **all** the template out otherwise it will be auto closed!
