### ISSUE TITLE
Client crashes on world load (unsupported modified version of game)

### ISSUE THREAD

**Issue by professorkintosh** [Darkosto/SevTech-Ages#2220]
# Issue / Bug:
Client crashes on world load, post Java update

# Expected Behavior
Client should not crash on world load after playing successfully for 50+ hours

# Possible Solution

# Steps to Reproduce (for bugs)
1. Update to the newest version of Java (64-bit)
2. Load (new) game from Twitch Launcher

# Context
I have deleted and re-installed Java, deleted my save file, deleted and re-installed Sevtech (twice). 
The error occurs as soon as the Loading World / Building Terrain screen schanges to 0%. It shuts down the server and the Minecraft launcher shows the game crash: 

> It looks like you are using an unsupported modified version of the game.  
The game crashed whilst unexpected error  
Error: java.lang.ExceptionInInitializerError
# Logs
Crash Log: [crash-2018-05-04_18.19.11-client.txt](https://github.com/Darkosto/SevTech-Ages/files/1976136/crash-2018-05-04_18.19.11-client.txt)

# Client Information: 
Modpack Version: 3.0.6
Java Version: Java 64-bit, version 8 update 171
Launcher Used: Twitch Launcher
Memory Allocated: 4096Mb
Server/LAN/Single Player: Singleplayer
Resourcepack Enabled?: No
Optifine Installed?: No

**Comment by artdude543** [comment]
According to the crash report, this was a file access issue from the mod trying to gain access to a folder. This could be caused by the gaming running in a share or the game not having correct permissions to write/read on the file system.

But this is not a fault of the mod or the pack. Ensure the permissions are accessible to the game & Java process.
