### ISSUE TITLE
Can't Find Rock Crystal Ore

### ISSUE THREAD

**Issue by NotHebbieJebbies** [Darkosto/SevTech-Ages#2236]
I'm on 3.0.6 and been in age 2 for a few days and I got to the point where I needed to find some rock crystals so I went out and found several samples, dug down to bedrock and found nothing; I tried clearing out large areas at bedrock and still nothing.

After six or seven failed attempts at finding it in survival mode I decided to go into created and really clear out the area, bedrock included and still found nothing in probably a 20x20x20 area underneath where the samples were.

I don't know if the ore is generally close to the X and Z coordinates of the samples but if not it really needs to be; I gave up and just creative mode-added some ore and mined it.

**Comment by Jandakast** [comment]
The ore should spawn in the chunk the samples spawned in. Rock Crystal generates below y10. In some instances the Rock crystal doesn't spawn because it tries to replace bedrock and can't or because a cave generates and removes the blocks that would have been the ore. A flat bedrock mod has been added to 3.0.7 to help prevent the scenario where bedrock blocks the spawn. 

Rock Crystal exists in the world. It's rareish but once you find a good vein you will be set.
