### ISSUE TITLE
Issue: Game crashes before menu screen

### ISSUE THREAD

**Issue by skateereer** [Darkosto/SevTech-Ages#2245]
## Issue/Bug
Game crashes before menu screen and goes back to the launcher.

## Expected Behavior
The menu should open.

## Possible Solution
No idea what cause of the crash is.

## Context
Can not open game so I cannot play.

## Logs
[latest.log](https://github.com/Darkosto/SevTech-Ages/files/1978143/latest.log)

## Client Information

* Modpack Version: 3.0.6
* Java Version: 8u172
* Launcher Used: Twitch

* Memory Allocated: 4,096MB

* Server/LAN/Single Player: 
* Resourcepack Enabled?:
* Optifine Installed?:

**Comment by Espergium** [comment]
It's crashing on trying to stitch textures together. Do you have enough VRAM?

**Comment by skateereer** [comment]
I've got 2048 MB of video memory, how much is necessary?

**Comment by artdude543** [comment]
1. Your MC install is broken use the Twitch Launcher to repair the base game.
2. The Texture Stitcher crash is known as MC alpha and will never get fixed. It's also random I.E. Comes and Go's. But this issue is not a pack issue.

Try the repair option above but if that does not help; you can ask Twitch Launcher support for help with the game install.

**Comment by skateereer** [comment]
Sorry to sound like an idiot but how do I repair the base game in the Twitch Launcher? Just create a new profile with no mods?

**Comment by Espergium** [comment]
Twitch launcher > click modpack profile > to towards the upper right and click the ". . ." button > should have a repair profile button.
