### ISSUE TITLE
[A8] Primal Core Stone ladder block

### ISSUE THREAD

**Issue by Dawenzel** [Darkosto/SevTech-Ages#226]
## Bug/Issue
I'm not sure if this is intended or not, but the Primal Core Stone ladder block lets through light even though it's a full block visually with no gaps at the sides. Will check if this also applies to the other ladder blocks.
![2017-11-28_00 42 54](https://user-images.githubusercontent.com/7070982/33295339-1ea07840-d3d5-11e7-806b-fe2d946c46ea.png)
This is the case for all the ladder blocks added by Primal Core.

## Versions
- Minecraft 1.12.2
- Forge 14.23.0.2544
- PrimalCore 0.6.8
- Java x64 8u144
- Sevtech-Ages Alpha 8

**Comment by Darkosto** [comment]
I'll ask the Primal Core dev to check this out when he can :) 

@An-Sar

**Comment by An-Sar** [comment]
i have fixed this in my dev, will be part of the next push

**Comment by Darkosto** [comment]
The inside of the ladder is still lit up but I believe we're as good as we can get on this one :)

**Comment by maximusv2004** [comment]
in a single player game, the cobblestone/stone blocks always face the same direction independent of whatever face was worked. i cant use them because of it. ex: i put some stone in a dirt wall to make a ladder. i start to use the workblade and it 'turn' to always face the same direction witch is inside the wall.
