### ISSUE TITLE
Investigate Why Viescraft Airship recipes are borked

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#276]
![image](https://user-images.githubusercontent.com/10309699/33784044-447d696e-dc2d-11e7-8727-b9f9dfbc28b0.png)

**Comment by GoryMoon** [comment]
I've looked into it some and all the extra recipes are there because you can craft any of the old airships into the new ones.
The reason it's not showing what item to input is because those items are hidden by the mod and that makes jei not show them in the recipes.

The different colors of airships represents the frame being used in the airship and all of those are upgraded in the GUI, so you only craft the base one and upgrade it. 
Also btw when applying an upgrade you get it back.

The only airships that should be craftable, not including the convertions, are the gray ones or as ids:
- vc:airships/item_airship_v1
- vc:airships/item_airship_v2
- vc:airships/item_airship_v3
- vc:airships/item_airship_v4

**Comment by Darkosto** [comment]
Looks like the latest update took care of this for us! Thank you for the information and help! :D
