### ISSUE TITLE
Sugi Forest causes a lot of lag

### ISSUE THREAD

**Issue by davqvist** [Darkosto/SevTech-Ages#36]
First I thought, it's just my computer, but a few other people told me they have the same problem. I already disabled Better Foliage, but even then if I stand in the middle of a Sugi Forest I can count my FPS on one hand while I usually have 50-100 FPS. I know Sevadus doesn't care if people can play the pack on their bad computers, but I still think this is worth noting.

**Comment by Jandakast** [comment]
I did some testing and this seems to be caused by looking through the leaves but any biome that has a dense amount of leaves seems to have the same effect. This doesn't seem to be an Issue with SevTech or the Sugi Forest mod.

In a test world with only Sugi Forest, HWYLA, and Quark installed. Difficulty set to peaceful and render distance 12.
Normal FPS in a planes biome is around 1200
FPS in Birch forest is steady at over 1000 no matter where I look
Standing still looking at the ground in a Sugi Forest I get over 1100 FPS. 
If I am looking anywhere that has a large amount of leaves being rendered my FPS is between 500 and 600.
I did the same testing in a Jungle and Spruce Forest and had the same results as in the Sugi Forest. 

Davqvist, can you find a jungle in your world and see if you get the same decrease in performance you get in the Sugi Forest?

**Comment by davqvist** [comment]
Well I was in other forests and sure I got some FPS drops, but in Sugi Forest I was in single digits. I mean I can do some tests again, sure.

**Comment by Darkosto** [comment]
Removed from pack LuL
