### ISSUE TITLE
Advancement Discription Text

### ISSUE THREAD

**Issue by GregsGirl04** [Darkosto/SevTech-Ages#444]
When mousing over certain advancements the text reads Lorem ipsum dolor sit amet.....
![2018-01-18_07 52 55](https://user-images.githubusercontent.com/35380539/35107094-e9666b8a-fc24-11e7-8d30-c0af900d1be2.png)

So far I have noticed it on:
Stg 0 Barrel of Vadis
Stg 2 The Market, Cinder Plinth, Aspectus, Alchemy Pedestal, and MEME Cannon.

I haven't progressed past Stg 2 yet so, not yet sure what others there are.

**Comment by ALongStringOfNumbers** [comment]
The descriptions for these advancements just have not been added yet. It is much more prevalent in the later stages I believe because those advancements are still in progress. It would probably be best to wait until Darkosto adds all the descriptions and then puts out a new version and then notify him of any descriptions that he missed.

**Comment by GregsGirl04** [comment]
Gotcha, thanks!

**Comment by Sparky1492** [comment]
@ALongStringOfNumbers, should we close this and start a new issues with a ToDo List in it?  If so, let me know and I will start the new issue with a ToDo List of all the Advancements that need to be updated/changed.

@GregsGirl04 , would this be ok with you?

**Comment by GregsGirl04** [comment]
Yes, that is fine.

**Comment by justinrusso** [comment]
See https://github.com/Darkosto/SevTech-Ages/issues/474
