### ISSUE TITLE
Alter Compact Machines Wall to Use Black Iron instead of iron block

### ISSUE THREAD

**Issue by Darkosto** [Darkosto/SevTech-Ages#522]

**Comment by Rixxaw** [comment]
I was just about to open an issue suggesting this is a bit much, seeing as we can only craft black Iron using the Alloy Furnace, which is somewhat incredibly slow.  For context.  In order to craft the minimal compact machine that can contain the Mixer and Dryer to make paper, you need 96 compact machine wall blocks, and that requires 54 black iron ingots, which take 27 minutes to smelt in the Alloy Furnace.

Add in the time to Crush the black quartz and then pack them using a Metal Presser, its closer to 45 minutes just to make 1 Compact machine that can contain the Modular machines for paper fabrication.

I suppose I could make more alloy furnaces, and I suppose I could put them all in a compact machine Kappa, but I just wasn't sure that was your intention when you made this change to create an artificial time sync.  The materials aren't really an issue its just the Alloy Furnace isn't able to be automated to my knowledge.  So even having all of your black quartz go into the alloy furnace to make black iron which is required on several recipes isn't really an option.  I will test modular routers and see if they can somehow push items into the furnace to automate it.
