### ISSUE TITLE
Torches

### ISSUE THREAD

**Issue by JackRuby1** [Darkosto/SevTech-Ages#638]
Some of my stage 1 coal torches turned themselves into stage 0 fiber torches, breaking one updated them into the right ones.

**Comment by Darkosto** [comment]
This is a visual bug from OreStages. I'm not sure how it could be fixed up to not happen.

@darkhax 

Basically, when the player is loading into a world or area some items show as their "hidden" variant. Usually, in single player it happens when I load my survival world and fixes itself after 5 seconds when everything is finished loading.

**Comment by justinrusso** [comment]
"So the issue here is that there are so many mods doing stuff when a player joins the world, that there is a que for mods to send their data."
