### ISSUE TITLE
The search for aquamarine advancement

### ISSUE THREAD

**Issue by Punkenstein** [Darkosto/SevTech-Ages#821]
when i first entered the beneath i got the full advancement for the search for aquamarine 2/2 without getting aquamarine. When i found aquamarine i mined it and then it fell out of my hand and said it was a block of platinum and i can not do anything with the ore.

**Comment by borg286** [comment]
I just entered the beneath in 3.0.3 and didn't get the aquamarine quest. Perhaps this is fixed now. I have to say it is a real pain finding it. The quest book says to look at the top of the caves and I've been searching for an hour and none to be found.  If you meant at the top layer then please rephrase to say the top of the beneath, rather than the top of the caves.

**Comment by borg286** [comment]
I ended up finding it. Please update the hint text to say "top of the Beneath" rather than the top of the caves. This will help prevent minecrafters from needlessly looking through caves, when you've configured them to spawn deep in the upper area behind a thick layer of cobblestone.

**Comment by Darkosto** [comment]
This should be fixed up now. If it persists for anyone please create a new issue.
