### ISSUE TITLE
Chunk Rendering Issues with SevTech v3.0.0

### ISSUE THREAD

**Issue by greatwhite18** [Darkosto/SevTech-Ages#837]
After a quick test, the pack can barely run at 60fps and cannot hit 60 stable with just running through a new world
micro-stuttering to large frame loss occurs on client chunk rendering
so this issue will probably not be helped very much by using a server
lowest framerate for 1 second averages : 32fps

Picture: https://imgur.com/a/277Be

Tested on 
Java: openjdk8 u162
Minecraft: 1.12.2
Forge: forge-14.23.2.2634
Modpack: 3.0.0

**Comment by Turkey2349** [comment]
I don't see the issue here. All worlds will incur some lag when generating new world terrain.

**Comment by greatwhite18** [comment]
Here is a video showing the issue provided: https://www.youtube.com/watch?v=WE6Ft-L7LLc&feature=youtu.be

**Comment by Turkey2349** [comment]
Honestly I don't see any issue with this beyond chuck generation or anything that is "fixable". I'll leave this open for now in case anyone has any ideas, but I don't think there is really anything that can be done other than you playing around with graphics settings.

**Comment by GirafiStudios** [comment]
Vsync could be causing this. Try turning vsync off, and setting the frame rate limit to 60 instead.
Does this happen after having loaded a world up for more than 10 minutes btw.?

**Comment by greatwhite18** [comment]
I have done this and seems to have made no difference. Yes, it keeps stuttering throughout the length of playing the pack. The pack is semi playable but wouldn't play due to the headache I get from seeing the game stutter every 5 seconds.

**Comment by artdude543** [comment]
I don't really see what the issue could be here; chunk generation will always be an issue as it's on the Minecraft Engine side. But the "stutter" your most likely getting is things going on in the world. There is not a whole lot we can do about that other than telling you to turn down settings and/or limit what applications you have running due to the world generation we use and the mods in use for masking blocks from stage locking and/or entities. It's far complex to explain in an issue. But it's kind of out of our power to "fix" as it's system/user based issue.

But yeah I can understand the frustration this will be causing you :/

On a side note: You're getting terrible performance on the 1050. Are your Drivers/Java up to date?
