### ISSUE TITLE
Issues with TwitchAPP

### ISSUE THREAD

**Issue by Nobruc** [Darkosto/SevTech-Ages#838]
After many years i'm returning to Minecraft because of SevTech Ages

but i'm experiencing many issues

-my launcher profile deletes itself after i close the game(i start the game from  twitchapp)
-mods always have to launch when i open the game which takes a good 10 minutes to load.

any ways i could install this without twitch app?

**Comment by Turkey2349** [comment]
There are ways to take twitch packs and move them over to multi mc (just google it should help). The pack is also available on ATLauncher as a public pack.

**Comment by Nobruc** [comment]
I did everything in multi Mc.. Seems better now.. St least SP I can play

Now I'm just running errors trying to connect and having my friends connect to the server... Ports are opened in router.. I do everything that the Readme says. Still can't connect.

**Comment by artdude543** [comment]
It looks like _may_ have a broken Twitch Launcher install; try to re-install it and re-setup things. I've never noticed it delete anything and the only time it deletes something is when updating a profile. But it backs this up beforehand. If something breaks during the process the backup is generally left untouched.

But deleting on when you close the game I highly doubt tbh, and I've used this Launcher since the early days and it's **never** done it. The game will take a while to load this will never change what ever you use to launch it.

But you can use the ATLauncher or MultiMC if you wish. With the server issue make sure the `server-ip` setting in the server.prop is blank (never fill that in unless you know what you're doing) and ensure it's listening on the right port and that you have forward the right one to the right computer on the network. And a silly one now make sure your friends are using the right IP. This should be your external one, not an internal one.
