### ISSUE TITLE
Shovels require more materials to repair then they do to craft them 

### ISSUE THREAD

**Issue by Ryzelf** [Darkosto/SevTech-Ages#847]
I have only experienced this with a stone shovel but i assume its the same for every shovel.
It just doesn't make sense to repair a shovel with 3 required materials if you can just craft a whole new one using less materials.

**Comment by Darkosto** [comment]
Yes, this is due to how the mod requires a static number of items to repair any tool. While it doesn't work out well for earlier tools, it works out more than fine for later on. This is not configurable per tool and not something we can fix and have extend to late game tools without serious exploit issues.

**Comment by Ryzelf** [comment]
ok thanks :)
