### ISSUE TITLE
AbyssalCraft Statue does nothing

### ISSUE THREAD

**Issue by Turmfalke2** [Darkosto/SevTech-Ages#896]
Nothing I do seems to be able to convince this statue to generate AbyssalCraft energy. Also pretty odd quest progression "Hey we got bronze ingots" -> "lets craft a necronomicon". Why am I doing this?

![2018-03-26_21 28 10](https://user-images.githubusercontent.com/5174562/37928346-d6a4ad84-313c-11e8-9fef-4f44b2e12b91.png)

3.0.1

**Comment by Darkosto** [comment]
Before I begin to test for this issue I'm going to comment on your questions regarding progression.

Firstly, the Necronomicon is needed for progression into Abyssalcraft so you can look up the needed information for the mod. So, why? Because it is handing the player information. 

Secondly, why start with Bronze? If you look in NEI there is a recipe for Bronze armor and other new items/blocks. Since, you need to locate and kill Shoggoths to progress you can use your newly found Bronze processing to make better armor since those mobs are very strong.

Not every single step will be given to you. Your job is fill in gaps between advancements with new items/blocks/etc.

Onto your issue, it looks like there is a tree above your statue? 

![image](https://user-images.githubusercontent.com/10309699/37930210-21ee8ef4-3110-11e8-8069-fda12584d267.png)

The Necronomicon gives you information about why it's not working.

**Comment by Turmfalke2** [comment]
Oh I must have missed the part about being under open sky.  
Also you seem to have a different font/size of the font that is much easier to read.
![2018-03-27_00 08 50](https://user-images.githubusercontent.com/5174562/37935767-11fac1be-3153-11e8-8920-e6f6a2f7cec2.png)
