### ISSUE TITLE
Slow server start

### ISSUE THREAD

**Issue by LemADEC** [Darkosto/SevTech-Ages#922]
As of SevTech 3.0.1 for Minecraft 1.12.2, the modpack takes more than 10 minutes to boot on a decent server with 4 to 8GB RAM allocated.
In the console, we can see the logs being silent for more than 30 seconds at times.

A partial profiling gives notably:
![image](https://user-images.githubusercontent.com/4776032/37938048-9341bbc0-315c-11e8-83c2-550baabe6d29.png)
More specifically, the top 2 contributors are:
![image](https://user-images.githubusercontent.com/4776032/37938135-f44260be-315c-11e8-84c7-c656fe4d68d8.png)
and
![image](https://user-images.githubusercontent.com/4776032/37938152-1731d640-315d-11e8-817d-e808cdb2508b.png)

That's ~5 minutes spent copying ItemStacks in CraftTweaker, on a partial profiler.

**Comment by artdude543** [comment]
Server side can be slow to start; but that's the same for the Client also. Not a whole lot that can be done tbh; unless we can track down something which is taking far to long to "run" but the Clients load at a fair time and the server is just short of that time. So really it's an "okay" time to deal with as a lot of changes is going on.

**Comment by artdude543** [comment]
On a side note, my server only takes 5 mins tops to boot from cold. With 8Gb allocated and last years Xeon.

**Comment by OscarXcore** [comment]
There is nothing you can really do unless you remove the scripts folder which is the whole pack.

**Comment by sarcastic6** [comment]
The only time I've seen it load that slowly is when I was trying it with Sponge.  Without sponge, the server launches in less than 5 minutes normally with 4gb allocated for me.

**Comment by artdude543** [comment]
Yeah, Vanilla Forge loading times are averaging around 5/8mins with semi-decent setups. Similar times being reported from server companies. So I'm not what else we can say/offer to help as this is something out the control of the pack; due to the changes we make.

All I can suggest is ensure your Java is up to date and/or using Java Args to help somewhat: https://pastebin.com/nV8aHRLE

**Comment by OscarXcore** [comment]
Sorry to reopen this but just to say, in my opinion, its all CPU speed based. I can prove this because the server companies using Xeons with average/common clocks of 3GHz are taking 5-8 Minutes. My OVH box that has an i7-7700K OC'ed to 5GHz just started a SevTech server in [2 minutes](https://i.imgur.com/oZHWgeC.png) 

Future reference to anyone that profiles a SevTech server and are questioning loading times, consider what you are using for specs first, and understand that the modpack isnt meant to be 'fast loading' or 'easy on computers'.

**Comment by LemADEC** [comment]
Those 10+ minutes are with sponge.
As the profiler shows, server spent more than 50% of its time just to copy ItemStack. There's certainly better ways to do the job without duplicating stacks all over.
