### ISSUE TITLE
Marble Bricks

### ISSUE THREAD

**Issue by RyanBerge** [Darkosto/SevTech-Ages#949]
It's not totally clear to me what the intended behavior here, but (at least in Age 1) Marble Bricks show up in JEI as craftable through a Luminous Crafting Table or with Chisel, but in reality you can craft them normally with a standard crafting table.

Either JEI should show the normal crafting recipe or the modpack should require the player to use the Luminous Crafting Table.

**Comment by artdude543** [comment]
This seems to be an intentional thing by AS as it adds the recipes but uses and Ore Dict and as it does not require any starlight it's treated as a normal recipe (not sure why it does not show in JEI). But I think it's an odd _quirk_ with the recipe adding. But crafting in a table/AS Luminous is fine.

Adding a recipe via CT may break things so I don't think it's a great idea but I'll make a note with the developer to maybe look into his recipe adding.
