### ISSUE TITLE
Really really laggy

### ISSUE THREAD

**Issue by KoKo-The-Rabbit** [Darkosto/SevTech-Ages#970]
When I found this modpack, I didn't think there would be any issues with running it since I play a lot of packs and don't have issues. I don't know if it's the size of the modpack or my computer but whenever I enter a world it's always so laggy to the point that I can barely move. Granted, the world has to load, but even after everything is created and loaded, I still lag all the time. Whenever I open the options, opening inventory, breaking or placing blocks, or even moving. I have really bad lag spikes all the time that last 2-3 seconds. I've tried turning snooper settings off, turning all extra things like shadows and clouds off in the settings, and changed the render distance to be fairly low. It's helped to some extent but I still get lag all the time. Any tips on what I can do?

**Comment by LoryMaster** [comment]
You should also list your system specs just to be sure. This is a very heavy weight pack, even for big packs standards.

1: Are you allocating enough RAM to minecraft? For this pack it seems that 6 GB is the bare minimum you need to allocate. I would personally recommend at least 8 GB. 

2: Are you adding extra recommended java arguments for garbage collection?
-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

3: Have you tried adding Optifine to the modpack? It can greatly help with performance.

4: Are you keeping open twitch livestreams while playing? Livestreams are CPU intensive, especially if you're playing them in 1080p60, and Minecraft loves to eat your CPU.

Performance issues need more information than just: "The game lags what can I do". You need to give plenty of information because, contrary to consoles, every single computer is different and will have different performance

**Comment by KoKo-The-Rabbit** [comment]
Ahh, I'm not a very tech savvy person, so I'm not entirely sure how to allocate RAM for it or anything. I don't usually watch twitch streams anyways, so I never have streams open when I play. I'm not sure how to add optifine to the pack, and I'm not entirely sure if I have the java arguments.

It would be cool if you could give me hand so I can figure this all out, I don't exactly know what I have to do to fix this. @LoryMaster

**Comment by KoKo-The-Rabbit** [comment]
@artdude543 I think so? I updated to the latest version of Java yesterday and it didn't do much

**Comment by KoKo-The-Rabbit** [comment]
Actually, never mind. I managed to allocate the ram I needed and now the it runs smoothly with little to no lag at all. Thanks for the tips ^^

**Comment by Wipperwill** [comment]
I'm having the same problem but mainly with opening inventory only. The thing I think it could be is that my Java isn't the most recent (1.8.0_25). I don't want to install the wrong Java to test this, can someone link me the correct download? Also perhaps some instructions how to add optifine if that might fix it?

Other than that, I am allocating 10Gig, my machine is leading edge running Windows 10, no other programs open except twitch launcher and Mozilla.

**Comment by oscarnyquist** [comment]
I got like 200fps after I change Algorithm to "Taylor's Algorithm" and preallocate memory to on in BetterFps Options and i also installed optifine

**Comment by niamh1212** [comment]
I have the same problem I allocated more ram and it helped a lot but it is still having random lag spikes.
While playing the game is the only thing I have open. This hasn't happened before so I am unsure on what to do.

**Comment by LuqDragon** [comment]
I installed the optifine and change the terrain animations to off and the lag spikes just gone, but you can change more configs to improve your FPS.

**Comment by coldReactive** [comment]
I'm pretty laggy as well, I tried the aforementioned garbage settings via launch options and installed optifine. When I set the RAM to 12 GB (Since that's not even half the 32 GB of RAM I have available) it gave me this error message when it finished loading and I tried to click single player:

The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.VerifyError: Bad type on operand stack
