### ISSUE TITLE
i run out of memory whenever i try to download the pack but still have plenty of space on my computer is there way to give more memory to the pack so that i can download it?

### ISSUE THREAD

**Issue by Borndwarf21** [Darkosto/SevTech-Ages#971]
### Before anything else, use the *search* feature!
 * Maybe someone already reported the issue you're experiencing?
 * Maybe you can find the answer to your question by looking at older or closed issues?
 * Have a go at it and see!
 
 ### Issue / bug
 - Explain the issue / bug as understandably as possible.
 - If possible add minecraft, forge, java and modpack version numbers for debugging (mod authors might need these).
 - If the issue/bug is recurring explain how it can be recreated (helps darkosto!).
 - If possible add error/crash log to [Pastebin](https://pastebin.com/) and link it here (if you dislike pastebin any other similar site is fine too).
 - If possible add a video/gif of the issue/bug (makes it easier for darkosto to understand you).

**Comment by gforero12** [comment]
@Buuz135 Did a decent job at explaining how to allocate more RAM towards Minecraft via the Twitch launcher although I'll explain in more detail just in case you didn't get it.

Step 1: Click the small arrow pointing down at the top right hand corner of the launcher.
![step_1](https://user-images.githubusercontent.com/36512658/37992702-5128d902-31c1-11e8-9e5a-44ed544065ee.png)

Step 2: Select "Settings" in order to open the settings panel.
![step_2](https://user-images.githubusercontent.com/36512658/37992721-5f4cd434-31c1-11e8-8387-31dc95887668.png)

Step 3: Select "Minecraft" from the settings panel.
![step_3](https://user-images.githubusercontent.com/36512658/37992735-6e4b77a6-31c1-11e8-8de8-b649771c8c69.png)

Step 4: Locate the purple bar allowing you to set the RAM allocated towards Minecraft. Usually 5GB (5,000 MB) is a good amount assuming your computer can handle that.
![step_4](https://user-images.githubusercontent.com/36512658/37992783-9111095e-31c1-11e8-94cf-5e81b582c91d.png)

Please close this issue if I solved it.

**Comment by Buuz135** [comment]
`I did not copy that text from google, or did I?`

**Comment by artdude543** [comment]
I'm closing this as you the way to fix the issue in text and image form. There is nothing more we can offer that other than us pricing a new machine for you to buy 😉
