### ISSUE TITLE
Summoning Parrot Gives No Advancement v3.0.3

### ISSUE THREAD

**Issue by ArbitraryHubris** [Darkosto/SevTech-Ages#983]
## Issue / Bug
Summoning a Parrot should give an advancement

## Current Behavior
Summoning works but no advancement

* Modpack Version: 3.0.3 - Server

**Comment by blay09** [comment]
The criteria appears to be taming of the parrot, however I've tamed two now and still did not get the achievement.

**Comment by ArbitraryHubris** [comment]
Yeah, 3 people on my server have summoned and tamed and none got the advancement

**Comment by Darkosto** [comment]
Interesting because I was able to complete it just fine when testing the advancement out.

**Comment by ArbitraryHubris** [comment]
This feature is a perfect solution to the difficulty in finding parrots, btw.

**Comment by ArbitraryHubris** [comment]
@Darkosto If you'd like to login to our server to see this, I'm happy to whitelist and op you so you can experiment

**Comment by Darkosto** [comment]
I think the issue here is a limitation of advancements work when requiring parents. 

When you have completed progress up to that advancement and then you update the pack it will not tick off having the parent competed while the new advancement exists. If you had started from scratch OR removed the previous adv. and given it back you could complete the new one.

The current solution, and what we have being coded right now is a way to allow new adv. to be made and still be completed. Hopefully, we can have this finished today to go out for 3.0.4.

https://twitter.com/DarkostoTV/status/979036486392799232
